// packages/website/src/examples/force-layout-graph/force-layout-graph.component.ts
import { Component } from '@angular/core'
import { GraphForceLayoutSettings, GraphLayoutType } from '@unovis/ts'

import { data, NodeDatum, LinkDatum } from './data'

@Component({
  selector: 'force-layout-graph',
  templateUrl: './force-layout-graph.component.html'
})
export class ForceLayoutGraphComponent {
  data = data
  layoutType = GraphLayoutType.Force

  forceLayoutSettings: GraphForceLayoutSettings = {
    forceXStrength: 0.2,
    forceYStrength: 0.2,
    charge: -700,
  }

  linkLabel = (l: LinkDatum) => ({ text: l.chapter })
  nodeLabel = (n: NodeDatum) => n.id
  nodeFill = (n: NodeDatum) => n.color
}

// packages/website/src/examples/force-layout-graph/force-layout-graph.svelte
<script lang='ts'>
  import { VisSingleContainer, VisGraph } from '@unovis/svelte'
  import { GraphForceLayoutSettings, GraphLayoutType } from '@unovis/ts'
  import { data, LinkDatum, NodeDatum } from './data'

  const forceLayoutSettings: GraphForceLayoutSettings = {
    forceXStrength: 0.2,
    forceYStrength: 0.4,
    charge: -700,
  }
  const linkLabel = (l: LinkDatum) => ({ text: l.chapter })
  const nodeLabel = (n: NodeDatum) => n.id
  const nodeFill = (n: NodeDatum) => n.color

</script>

<VisSingleContainer {data} height={600}>
  <VisGraph
    layoutType="{GraphLayoutType.Force}"
    nodeSize={40}
    {forceLayoutSettings}
    {linkLabel}
    {nodeFill}
    {nodeLabel}
  />
</VisSingleContainer>
