// packages/vue/src/components/plotband/index.vue
<script setup lang="ts" generic="Datum">
// !!! This code was automatically generated. You should not change it !!!

import type { PlotbandConfigInterface } from '@unovis/ts/components/plotband/config'
import { Plotband } from '@unovis/ts/components/plotband'
import { inject, nextTick, onMounted, onUnmounted, ref, watch } from 'vue'
import { componentAccessorKey } from '../../utils/context'
import { arePropsEqual, useForwardProps } from '../../utils/props'

const props = defineProps<Props & { data?: null }>()

const accessor = inject(componentAccessorKey)

// data and required props
type Props = PlotbandConfigInterface<Datum>
// config
const config = useForwardProps(props)

// component declaration
const component = ref<Plotband<Datum>>()

onMounted(() => {
  nextTick(() => {
    component.value = new Plotband<Datum>(config.value)

    accessor.update(component.value)
  })
})

onUnmounted(() => {
  component.value?.destroy()
  accessor.destroy()
})

watch(config, (curr, prev) => {
  if (!arePropsEqual(curr, prev)) {
    component.value?.setConfig(config.value)
    component.value?.render()
  }
})

defineExpose({
  component,
})
</script>

<script lang="ts">
export const VisPlotbandSelectors = Plotband.selectors
</script>

<template>
  <div data-vis-component />
</template>

// packages/svelte/src/components/plotband/plotband.svelte
<script lang="ts">
  // !!! This code was automatically generated. You should not change it !!!
  import { Plotband } from '@unovis/ts/components/plotband'
  import type { PlotbandConfigInterface } from '@unovis/ts/components/plotband/config'
  import { onMount, getContext } from 'svelte'

  import type { Lifecycle } from '../../types/context'
  import { arePropsEqual } from '../../utils/props'
  // type defs
  type Datum = $$Generic

  // config
  let prevConfig: PlotbandConfigInterface<Datum>
  let config: PlotbandConfigInterface<Datum>
  $: config = { ...$$restProps }

  // component declaration
  let component: Plotband<Datum>
  const lifecycle = getContext<Lifecycle>('component')

  onMount(() => {
    component = new Plotband<Datum>(config)
    return () => component?.destroy()
  })
  $: if (!arePropsEqual(prevConfig, config)) {
    component?.setConfig(config)
    prevConfig = config
  }

  // component accessor
  export function getComponent (): Plotband<Datum> { return component }

</script>

<vis-component use:lifecycle={component}/>
