// packages/vis-angular/src/containers/xy-container/xy-container.component.ts
// Copyright (c) Volterra, Inc. All rights reserved.
import {
  Component,
  ViewChild,
  ContentChildren,
  ContentChild,
  ElementRef,
  AfterViewInit,
  Input,
  OnDestroy,
  QueryList,
  SimpleChanges,
} from '@angular/core'

// Vis
import { XYComponentCore, XYContainer, XYContainerConfigInterface, Axis, Crosshair, Tooltip, Dimension } from '@volterra/vis'
import { VisXYComponent } from '../../core'
import { VisTooltipComponent } from '../../core/tooltip/tooltip.directive'

@Component({
  selector: 'vis-xy-container',
  template: `<div #container class="container">
    <ng-content></ng-content>
  </div>`,
  styles: ['.container { width: 100%; height: 100%; position: relative; }'],
})
export class VisXYContainerComponent<Datum = Record<string, unknown>> implements AfterViewInit, OnDestroy {
  @ViewChild('container', { static: false }) containerRef: ElementRef
  @ContentChildren(VisXYComponent) visComponents: QueryList<VisXYComponent>
  @ContentChild(VisTooltipComponent) tooltipComponent: VisTooltipComponent
  @Input() duration: number = undefined
  @Input() margin = { top: 10, bottom: 10, left: 10, right: 10 }
  @Input() padding = {}
  @Input() dimensions: { x: Dimension; y: Dimension } = { x: {}, y: {} }
  @Input() adaptiveYScale
  @Input() data: Datum[] = []
  chart: XYContainer<Datum>

  ngAfterViewInit (): void {
    this.chart = new XYContainer<Datum>(this.containerRef.nativeElement, this.getConfig(), this.data)
  }

  ngOnChanges (changes: SimpleChanges): void {
    const preventRender = true

    // Set new Data without re-render
    if (changes.data) {
      this.chart?.setData(this.data, preventRender)
      delete changes.data
    }

    // Update Container and render
    this.chart?.updateContainer(this.getConfig())
  }

  getConfig (): XYContainerConfigInterface<Datum> {
    const { duration, margin, padding, dimensions, adaptiveYScale } = this
    const visComponents = this.visComponents.toArray().map(d => d.component)

    const crosshair = visComponents.find(c => c instanceof Crosshair) as Crosshair<Datum>
    const tooltip = this.tooltipComponent?.component as Tooltip<XYComponentCore<Datum>, Datum>
    const xAxis = visComponents.find(c => c instanceof Axis && c?.config?.type === 'x') as Axis<Datum>
    const yAxis = visComponents.find(c => c instanceof Axis && c?.config?.type === 'y') as Axis<Datum>
    const axes: {x?: Axis<Datum>; y?: Axis<Datum>} = {}
    if (xAxis) axes.x = xAxis
    if (yAxis) axes.y = yAxis

    const components = visComponents.filter(c => !(c instanceof Crosshair) && !(c instanceof Tooltip) && !(c instanceof Axis))

    return { components, duration, margin, padding, dimensions, axes, tooltip, crosshair, adaptiveYScale }
  }

  ngOnDestroy (): void {
    this.chart?.destroy()
  }
}

<div #container class="xy-container">
    <ng-content></ng-content>
</div>

// packages/vis-react/src/containers/xy-container/index.tsx
// Copyright (c) Volterra, Inc. All rights reserved.
/* eslint-disable @typescript-eslint/naming-convention */
import { ReactNode, useEffect, useRef, useState } from 'react'
import { XYContainer, XYContainerConfigInterface, XYComponentCore, Tooltip, Crosshair, Axis, AxisType } from '@volterra/vis'

// Types
import { VisComponentElement } from 'src/types/dom'

export type VisXYContainerProps<Datum> = XYContainerConfigInterface<Datum> & {
  data?: Datum[];
  children?: ReactNode | undefined;
}

// eslint-disable-next-line @typescript-eslint/naming-convention
export function VisXYContainer<Datum> (props: VisXYContainerProps<Datum>): JSX.Element {
  const container = useRef<HTMLDivElement>(null)
  const [chart, setChart] = useState<XYContainer<Datum>>()

  const getConfig = (): XYContainerConfigInterface<Datum> => ({
    components: Array
      .from(container.current?.querySelectorAll<VisComponentElement<XYComponentCore<Datum>>>('vis-component') ?? [])
      .map(c => c.__component__),
    tooltip: container.current?.querySelector<VisComponentElement<Tooltip>>('vis-tooltip')?.__component__,
    crosshair: container.current?.querySelector<VisComponentElement<Crosshair<Datum>>>('vis-crosshair')?.__component__,
    xAxis: Array
      .from(container.current?.querySelectorAll<VisComponentElement<Axis<Datum>>>('vis-tooltip') ?? [])
      .map(c => c.__component__)
      .find(c => c.config.type === AxisType.X),
    yAxis: Array
      .from(container.current?.querySelectorAll<VisComponentElement<Axis<Datum>>>('vis-tooltip') ?? [])
      .map(c => c.__component__)
      .find(c => c.config.type === AxisType.Y),
    ...props,
  })

  // On Mount
  useEffect(() => {
    setChart(
      new XYContainer<Datum>(container.current as HTMLDivElement, getConfig(), props.data ?? [])
    )

    return () => chart?.destroy()
  }, [])

  // On Props Update
  useEffect(() => {
    const preventRender = true

    // Set new Data without re-render
    chart?.setData(props.data ?? [], preventRender)

    // Update Container and render
    chart?.updateContainer(getConfig())
  })

  return (
    <div ref={container} style={{ width: '100%', height: '100%', position: 'relative' }}>
      {props.children}
    </div>
  )
}
