// packages/solid/src/html-components/leaflet-map/index.tsx
// !!! This code was automatically generated. You should not change it !!!
import { LeafletMap } from "@unovis/ts/components/leaflet-map";
import type { LeafletMapConfigInterface } from "@unovis/ts/components/leaflet-map/config";
import type { GenericDataRecord } from "@unovis/ts/types/data";
import { createSignal, onCleanup, createEffect, on, onMount } from 'solid-js'
import { arePropsEqual } from '../../utils/props'

export type VisLeafletMapProps<Datum extends GenericDataRecord> = LeafletMapConfigInterface<Datum>& {
  data?: Datum[];
};

export const VisLeafletMapSelectors = LeafletMap.selectors

export function VisLeafletMap<Datum extends GenericDataRecord>(props: VisLeafletMapProps<Datum>) {
  const [component, setComponent] = createSignal<LeafletMap<Datum>>()
   
  const [ref, setRef] = createSignal<HTMLDivElement>()

  onMount(() => {
    const r = ref()
    if(r) setComponent(new LeafletMap<Datum>(r, props, props.data));
    
    
  })

  onCleanup(() => {
    component()?.destroy()
    
  })

  createEffect(
    on(
      () => ({ ...props }),
      (curr, prev) => {
        if (!arePropsEqual(prev, curr)) {
          component()?.setConfig(curr)
          
        }
      },
      {
        defer: true
      }
    )
  )

  

  return <div  ref={setRef} style={{ display:"block", position:"relative" }} />
}

// packages/vue/src/html-components/leaflet-map/index.vue
<script setup lang="ts" generic="Datum extends GenericDataRecord">
// !!! This code was automatically generated. You should not change it !!!

import type { LeafletMapConfigInterface } from '@unovis/ts/components/leaflet-map/config'
import type { GenericDataRecord } from '@unovis/ts/types/data'
import { LeafletMap } from '@unovis/ts/components/leaflet-map'
import { computed, nextTick, onMounted, onUnmounted, ref, watch } from 'vue'
import { arePropsEqual, useForwardProps } from '../../utils/props'

// data and required props
type Props = LeafletMapConfigInterface<Datum>
const props = defineProps<Props & { data?: Datum[] }>()

const data = computed(() => props.data)
// config
const config = useForwardProps(props)

// component declaration
const component = ref<LeafletMap<Datum>>()
const elRef = ref<HTMLDivElement>()

onMounted(() => {
  nextTick(() => {
    if (elRef.value)
      component.value = new LeafletMap<Datum>(elRef.value, config.value, data.value)
  })
})

onUnmounted(() => {
  component.value?.destroy()
})

watch(config, (curr, prev) => {
  if (!arePropsEqual(curr, prev)) {
    component.value?.setConfig(config.value)
    component.value?.render()
  }
})

watch(data, () => {
  component.value?.setData(data.value)
})

defineExpose({
  component,
})
</script>

<script lang="ts">
export const VisLeafletMapSelectors = LeafletMap.selectors
</script>

<template>
  <div ref="elRef" data-vis-leaflet-map />
</template>

<style>
  [data-vis-leaflet-map] {
    display:block;
    position:relative;
  }
</style>
