// packages/website/src/examples/basic-timeline/basic-timeline.tsx
import React, { useCallback } from 'react'
import { Timeline } from '@unovis/ts'
import { VisXYContainer, VisBulletLegend, VisTooltip, VisTimeline, VisAxis } from '@unovis/react'

import { colorMap, data, DataRecord, ProductType } from './data'

const labelWidth = 220
const dateFormatter = Intl.DateTimeFormat().format

export default function BasicTimeline (): JSX.Element {
  const legendItems = Object.keys(ProductType).map((name) => ({ name, color: colorMap[name] }))

  function getTooltipText (_: string, i: number): string {
    const { startDate, endDate, description } = data[i]
    return `
      <div style="width:${labelWidth}px">
        ${[startDate, endDate].map(dateFormatter).join(' - ')}
        ${description}
      </div>`
  }

  return (
    <VisXYContainer data={data} height={'50vh'}>
      <h3>A Timeline of Abandoned Google Products, 1997 - 2022</h3>
      <VisBulletLegend items={legendItems}/>
      <VisTimeline
        x={useCallback((d: DataRecord) => d.startDate, [])}
        length={useCallback((d: DataRecord) => d.endDate - d.startDate, [])}
        type={useCallback((d: DataRecord) => d.name, [])}
        color={useCallback((d: DataRecord) => colorMap[d.type], [])}
        labelWidth={labelWidth}
        showLabels={true}
      />
      <VisTooltip triggers={{
        [Timeline.selectors.label]: getTooltipText,
      }}/>
      <VisAxis type="x" tickFormat={dateFormatter} numTicks={10}/>
    </VisXYContainer>
  )
}

// packages/shared/examples/basic-timeline/basic-timeline-solid.tsx
import { JSX } from 'solid-js'
import { Timeline } from '@unovis/ts'
import { VisAxis, VisBulletLegend, VisTimeline, VisTooltip, VisXYContainer } from '@unovis/solid'

import { colorMap, data, DataRecord, ProductType } from './data'

const BasicTimeline = (): JSX.Element => {
  const labelWidth = 220
  const dateFormatter = Intl.DateTimeFormat().format

  function getTooltipText (_: string, i: number): string {
    const { startDate, endDate, description } = data[i]
    return `
      <div style="width:${labelWidth}px">
        ${[startDate, endDate].map(dateFormatter).join(' - ')}
        ${description}
      </div>`
  }

  const x = (d: DataRecord) => d.startDate
  const length = (d: DataRecord) => d.endDate - d.startDate
  const type = (d: DataRecord) => d.name
  const color = (d: DataRecord) => colorMap[d.type]

  const legendItems = Object.keys(ProductType).map((name, i) => ({
    name,
    color: colorMap[name],
  }))
  const triggers = { [Timeline.selectors.label]: getTooltipText }

  return (
    <VisXYContainer data={data} height='50dvh'>
      <h3>A Timeline of Abandoned Google Products, 1997 - 2022</h3>
      <VisBulletLegend items={legendItems} />
      <VisTimeline
        x={x}
        length={length}
        type={type}
        color={color}
        labelWidth={labelWidth}
        showLabels
      />
      <VisTooltip triggers={triggers} />
      <VisAxis type='x' numTicks={10} tickFormat={dateFormatter} />
    </VisXYContainer>
  )
}

export default BasicTimeline
