// packages/solid/src/components/stacked-bar/index.tsx
// !!! This code was automatically generated. You should not change it !!!
import { StackedBar } from "@unovis/ts/components/stacked-bar";
import type { StackedBarConfigInterface } from "@unovis/ts/components/stacked-bar/config";
import { createSignal, onCleanup, createEffect, on, onMount } from 'solid-js'
import { arePropsEqual } from '../../utils/props'
import { useVisContainer } from "../../utils/context";

export type VisStackedBarProps<Datum> = StackedBarConfigInterface<Datum>& {
  data?: Datum[];
};

export const VisStackedBarSelectors = StackedBar.selectors

export function VisStackedBar<Datum>(props: VisStackedBarProps<Datum>) {
  const [component, setComponent] = createSignal<StackedBar<Datum>>()
   const ctx = useVisContainer();
  
  onMount(() => {
    setComponent(new StackedBar<Datum>(props));
    if (props.data) component()?.setData(props.data)
    ctx.update("component", component);
  })

  onCleanup(() => {
    component()?.destroy()
    ctx.destroy("component");
  })

  createEffect(
    on(
      () => ({ ...props }),
      (curr, prev) => {
        if (!arePropsEqual(prev, curr)) {
          component()?.setConfig(curr)
          ctx.dirty()
        }
      },
      {
        defer: true
      }
    )
  )

  
  createEffect(
    on(
      () => props.data,
      (data) => {
        if (data) {
          component()?.setData(data)
          ctx.dirty()
        }
      },
      {
        defer: true
      }
    )
  );


  return <div data-vis-component  />
}

// packages/vue/src/components/stacked-bar/index.vue
<script setup lang="ts" generic="Datum">
// !!! This code was automatically generated. You should not change it !!!

import type { StackedBarConfigInterface } from '@unovis/ts/components/stacked-bar/config'
import { StackedBar } from '@unovis/ts/components/stacked-bar'
import { computed, inject, nextTick, onMounted, onUnmounted, ref, watch } from 'vue'
import { componentAccessorKey } from '../../utils/context'
import { arePropsEqual, useForwardProps } from '../../utils/props'

const props = defineProps<Props & { data?: Datum[] }>()

const accessor = inject(componentAccessorKey)

// data and required props
type Props = StackedBarConfigInterface<Datum>
const data = computed(() => accessor.data.value ?? props.data)
// config
const config = useForwardProps(props)

// component declaration
const component = ref<StackedBar<Datum>>()

onMounted(() => {
  nextTick(() => {
    component.value = new StackedBar<Datum>(config.value)
    component.value?.setData(data.value)
    accessor.update(component.value)
  })
})

onUnmounted(() => {
  component.value?.destroy()
  accessor.destroy()
})

watch(config, (curr, prev) => {
  if (!arePropsEqual(curr, prev)) {
    component.value?.setConfig(config.value)
    component.value?.render()
  }
})

watch(data, () => {
  component.value?.setData(data.value)
})

defineExpose({
  component,
})
</script>

<script lang="ts">
export const VisStackedBarSelectors = StackedBar.selectors
</script>

<template>
  <div data-vis-component />
</template>
