// packages/shared/examples/synchronized-crosshair/synchronized-crosshair.vue
<template>
  <div style="display: flex; flex-direction: column; gap: 20px;">
    <div>
      <h4>Line Chart</h4>
      <VisXYContainer :data="data1" :height="height">
        <VisLine :x="x" :y="y" />
        <VisCrosshair syncId="demo-sync" :template="tooltipTemplate" />
        <VisTooltip />
        <VisAxis type="x" />
        <VisAxis type="y" />
      </VisXYContainer>
    </div>

    <div>
      <h4>Area Chart</h4>
      <VisXYContainer :data="data2" :height="height">
        <VisArea :x="x" :y="y" />
        <VisCrosshair syncId="demo-sync" :template="tooltipTemplate" />
        <VisTooltip />
        <VisAxis type="x" />
        <VisAxis type="y" />
      </VisXYContainer>
    </div>

    <div>
      <h4>Scatter Plot</h4>
      <VisXYContainer :data="data3" :height="height">
        <VisScatter :x="x" :y="y" />
        <VisCrosshair syncId="demo-sync" :template="tooltipTemplate" />
        <VisTooltip />
        <VisAxis type="x" />
        <VisAxis type="y" />
      </VisXYContainer>
    </div>

    <div style="font-size: 14px; color: #666; text-align: center; margin-top: 10px;">
      Hover over any chart to see synchronized crosshairs across all three charts
    </div>
  </div>
</template>

<script setup lang="ts">
import { VisXYContainer, VisLine, VisArea, VisScatter, VisAxis, VisCrosshair, VisTooltip } from '@unovis/vue'
import { data1, data2, data3, type DataRecord } from './data'

const height = 200

const x = (d: DataRecord) => d.x
const y = (d: DataRecord) => d.y

const tooltipTemplate = (d: DataRecord): string => {
  return `<div><b>X: ${d.x}</b><br/>Y: ${d.y.toFixed(1)}<br/>Y1: ${d.y1.toFixed(1)}<br/>Y2: ${d.y2.toFixed(1)}</div>`
}
</script>

// packages/shared/examples/synchronized-crosshair/synchronized-crosshair.component.ts
import { Component } from '@angular/core'
import { data1, data2, data3, DataRecord } from './data'

@Component({
  selector: 'synchronized-crosshair',
  templateUrl: './synchronized-crosshair.component.html',
})
export class SynchronizedCrosshairComponent {
  x = (d: DataRecord): number => d.x
  y = (d: DataRecord): number => d.y
  data1 = data1
  data2 = data2
  data3 = data3
  height = 200
  syncId = 'demo-sync'

  tooltipTemplate = (d: DataRecord): string => {
    return `<div><b>X: ${d.x}</b><br/>Y: ${d.y.toFixed(1)}<br/>Y1: ${d.y1.toFixed(1)}<br/>Y2: ${d.y2.toFixed(1)}</div>`
  }
}

<div style="display: flex; flex-direction: column; gap: 20px;">
  <div>
    <h4>Line Chart</h4>
    <vis-xy-container [data]="data1" [height]="height">
      <vis-line [x]="x" [y]="y"></vis-line>
      <vis-crosshair [syncId]="syncId" [template]="tooltipTemplate"></vis-crosshair>
      <vis-tooltip></vis-tooltip>
      <vis-axis type="x"></vis-axis>
      <vis-axis type="y"></vis-axis>
    </vis-xy-container>
  </div>

  <div>
    <h4>Area Chart</h4>
    <vis-xy-container [data]="data2" [height]="height">
      <vis-area [x]="x" [y]="y"></vis-area>
      <vis-crosshair [syncId]="syncId" [template]="tooltipTemplate"></vis-crosshair>
      <vis-tooltip></vis-tooltip>
      <vis-axis type="x"></vis-axis>
      <vis-axis type="y"></vis-axis>
    </vis-xy-container>
  </div>

  <div>
    <h4>Scatter Plot</h4>
    <vis-xy-container [data]="data3" [height]="height">
      <vis-scatter [x]="x" [y]="y"></vis-scatter>
      <vis-crosshair [syncId]="syncId" [template]="tooltipTemplate"></vis-crosshair>
      <vis-tooltip></vis-tooltip>
      <vis-axis type="x"></vis-axis>
      <vis-axis type="y"></vis-axis>
    </vis-xy-container>
  </div>

  <div style="font-size: 14px; color: #666; text-align: center; margin-top: 10px;">
    Hover over any chart to see synchronized crosshairs across all three charts
  </div>
</div>
