// packages/shared/examples/elk-layered-graph/elk-layered-graph.component.ts
import { Component } from '@angular/core'
import { GraphLayoutType, GraphNodeShape } from '@unovis/ts'

import { data, NodeDatum, panels } from './data'

@Component({
  selector: 'elk-graph',
  templateUrl: './elk-layered-graph.component.html',
  styleUrls: ['./styles.css'],
})
export class ElkLayeredGraphComponent {
  data = data
  layoutType = GraphLayoutType.Elk

  nodeShape = GraphNodeShape.Square
  nodeStrokeWidth = 1.5
  nodeLabel = (n: NodeDatum): string => n.id
  panels = panels
  layoutElkNodeGroups = [
    (d: NodeDatum): string | null => d.group ?? null,
    (d: NodeDatum): string | null => d.subGroup ?? null,
  ]

  layoutElkSettings = {
    'layered.crossingMinimization.forceNodeModelOrder': 'true',
    'elk.direction': 'RIGHT',
    'elk.padding': '[top=30.0,left=10.0,bottom=30.0,right=10.0]',
    'nodePlacement.strategy': 'SIMPLE',
  }
}

<div class="chart">
  <vis-single-container [data]="data" height="60vh">
      <vis-graph
        [layoutType]="layoutType"
        [nodeShape]="nodeShape"
        [nodeStrokeWidth]="nodeStrokeWidth"
        [nodeLabel]="nodeLabel"
        [layoutElkNodeGroups]="layoutElkNodeGroups"
        [layoutElkSettings]="layoutElkSettings"
        [panels]="panels"
        [disableZoom]="false"
      ></vis-graph>
  </vis-single-container>
</div>

// packages/shared/examples/elk-layered-graph/elk-layered-graph-solid.tsx
import { JSX } from 'solid-js'
import { GraphLayoutType, GraphNodeShape } from '@unovis/ts'
import { VisGraph, VisSingleContainer } from '@unovis/solid'

import './styles.css'

import { data, NodeDatum, panels } from './data'

const ElkLayerdGraph = (): JSX.Element => {
  const layoutElkSettings = {
    'layered.crossingMinimization.forceNodeModelOrder': 'true',
    'elk.direction': 'RIGHT',
    'elk.padding': '[top=30.0,left=10.0,bottom=30.0,right=10.0]',
    'nodePlacement.strategy': 'SIMPLE',
  }

  const nodeShape = GraphNodeShape.Square
  const nodeStrokeWidth = 1.5
  const nodeLabel = (n: NodeDatum) => n.id
  const layoutType = GraphLayoutType.Elk
  const layoutElkNodeGroups = [
    (d: NodeDatum) => d.group ?? null,
    (d: NodeDatum) => d.subGroup ?? null,
  ]

  return (
    <div class="chart">
      <VisSingleContainer data={data} height="50dvh">
        <VisGraph
          nodeShape={nodeShape}
          nodeStrokeWidth={nodeStrokeWidth}
          nodeLabel={nodeLabel}
          layoutType={layoutType}
          layoutElkNodeGroups={layoutElkNodeGroups}
          layoutElkSettings={layoutElkSettings}
          panels={panels}
          disableZoom
        />
      </VisSingleContainer>
    </div>
  )
}

export default ElkLayerdGraph
