// packages/website/src/examples/basic-line-chart/basic-line-chart.tsx
import React, { useCallback } from 'react'
import { VisXYContainer, VisLine, VisAxis } from '@unovis/react'

import { data } from './data'

export default function BasicLineChart (): JSX.Element {
  return (
    <VisXYContainer height={600}>
      <VisLine
        data={data}
        x={useCallback(d => d.x, [])}
        y={useCallback(d => d.y, [])}
      ></VisLine>
      <VisAxis type="x"></VisAxis>
      <VisAxis type="y"></VisAxis>
    </VisXYContainer>
  )
}

// packages/shared/examples/basic-line-chart/basic-line-chart.vue
<script setup lang="ts">
import { VisXYContainer, VisLine, VisAxis } from '@unovis/vue'
import { data } from './data'
</script>

<template>
  <VisXYContainer :height="600">
    <VisLine :data :x="d => d.x" :y="d => d.y" />
    <VisAxis type="x" />
    <VisAxis type="y" />
  </VisXYContainer>
</template>
