// packages/svelte/src/components/annotations/annotations.svelte
<script lang="ts">
  /* eslint-disable @typescript-eslint/no-unsafe-return */
  // !!! This code was automatically generated. You should not change it !!!
  import { Annotations, AnnotationsConfigInterface, AnnotationDatum } from '@unovis/ts'
  import { onMount, getContext } from 'svelte'

  import type { Lifecycle } from '../../types/context'
  import { arePropsEqual } from '../../utils/props'
  // type defs
  type Datum = $$Generic<AnnotationDatum>

  // data and required props
  // eslint-disable-next-line no-undef-init
  export let data: Datum[] = undefined

  // config
  let prevConfig: AnnotationsConfigInterface<Datum>
  let config: AnnotationsConfigInterface<Datum>
  $: config = { ...$$restProps }

  // component declaration
  let component: Annotations<Datum>
  const lifecycle = getContext<Lifecycle>('annotations')

  onMount(() => {
    component = new Annotations<Datum>(config)
    return (): void => component?.destroy()
  })
  $: component?.setData(data)
  $: if (!arePropsEqual(prevConfig, config)) {
    component?.setConfig(config)
    prevConfig = config
  }

  // component accessor
  export function getComponent (): Annotations<Datum> { return component }

</script>

<vis-annotations use:lifecycle={component}/>

// packages/react/src/components/annotations/index.tsx
// !!! This code was automatically generated. You should not change it !!!
import React, { ForwardedRef, Ref, useImperativeHandle, useEffect, useRef, useState } from 'react'
import { Annotations, AnnotationsConfigInterface } from '@unovis/ts'

// Utils
import { arePropsEqual } from 'src/utils/react'

// Types
import { VisComponentElement } from 'src/types/dom'

export type VisAnnotationsRef<> = {
  component?: Annotations<>;
}

export type VisAnnotationsProps<> = AnnotationsConfigInterface<> & {
  data?: Datum[];
  ref?: Ref<VisAnnotationsRef<>>;
}

// eslint-disable-next-line @typescript-eslint/naming-convention
function VisAnnotationsFC<> (props: VisAnnotationsProps<>, fRef: ForwardedRef<VisAnnotationsRef<>>): JSX.Element {
  const ref = useRef<VisComponentElement<Annotations<>>>(null)
  const componentRef = useRef<Annotations<> | undefined>(undefined)

  // On Mount
  useEffect(() => {
    const element = (ref.current as VisComponentElement<Annotations<>>)

    const c = new Annotations<>(props)
    componentRef.current = c
    element.__component__ = c

    return () => {
      componentRef.current = undefined
      c.destroy()
    }
  }, [])

  // On Props Update
  useEffect(() => {
    const component = componentRef.current
    if (props.data) component?.setData(props.data)
    component?.setConfig(props)
  })

  useImperativeHandle(fRef, () => ({ component: componentRef.current }), [componentRef.current])
  return <vis-annotations ref={ref} />
}

// We export a memoized component to avoid unnecessary re-renders
//  and define its type explicitly to help react-docgen-typescript to extract information about props
export const VisAnnotations: (<>(props: VisAnnotationsProps<>) => JSX.Element | null) = React.memo(React.forwardRef(VisAnnotationsFC), arePropsEqual)
