// packages/shared/examples/basic-sankey/basic-sankey-solid.tsx
import { JSX } from 'solid-js'
import { FitMode } from '@unovis/ts'
import { VisSankey, VisSingleContainer } from '@unovis/solid'

import { data, NodeDatum } from './data'

const BasicSankey = (): JSX.Element => {
  const subLabel = (d: NodeDatum) => `£${d.value.toFixed(2)}`

  return (
    <VisSingleContainer data={data} height='50dvh'>
      <VisSankey
        labelFit={FitMode.Wrap}
        labelForceWordBreak={false}
        labelMaxWidth={150}
        nodePadding={20}
        subLabel={subLabel}
      />
    </VisSingleContainer>
  )
}

export default BasicSankey

// packages/website/src/examples/basic-sankey/basic-sankey.tsx
import React, { useCallback } from 'react'
import { FitMode } from '@unovis/ts'
import { VisSingleContainer, VisSankey } from '@unovis/react'

import { data, NodeDatum } from './data'

export default function BasicSankey (): JSX.Element {
  return (
    <VisSingleContainer data={data} height={400}>
      <VisSankey
        labelFit={FitMode.Wrap}
        labelForceWordBreak={false}
        labelMaxWidth={150}
        nodePadding={20}
        subLabel={useCallback((d: NodeDatum) => `£${d.value.toFixed(2)}`, [])}
      />
    </VisSingleContainer>
  )
}
