// packages/vue/src/html-components/bullet-legend/index.vue
<script setup lang="ts" >
// !!! This code was automatically generated. You should not change it !!!
import { BulletLegend, BulletLegendConfigInterface, BulletLegendItemInterface } from '@unovis/ts'
import { onMounted, onUnmounted, computed, ref, watch, nextTick } from 'vue'
import { arePropsEqual, useForwardProps } from '../../utils/props'


// data and required props 
interface Props extends  BulletLegendConfigInterface { }
const props = defineProps<Props & { data?: null }>()

const data = computed(() => props.data)
// config
const config = useForwardProps(props)

// component declaration
const component = ref<BulletLegend>()
const elRef = ref<HTMLDivElement>()

onMounted(() => {
  nextTick(() => {
    if(elRef.value)
    component.value = new BulletLegend(elRef.value, config.value)
    
    
  })
})

onUnmounted(() => {
  component.value?.destroy()
  
})

watch(config, (curr, prev) => {
  if (!arePropsEqual(curr, prev)) {
    component.value?.update(config.value)
  }
})


defineExpose({
  component
})
</script>

<template>
  <div data-vis-bullet-legend ref="elRef"/>
</template>


<style>
  [data-vis-bullet-legend] {
    display:block;
  }
</style>

// packages/vis-svelte/src/html-components/bullet-legend/bullet-legend.svelte
<script lang="ts">
  // !!! This code was automatically generated. You should not change it !!!
  import { BulletLegend, BulletLegendConfigInterface, BulletLegendItemInterface } from '@unovis/ts'
  import { onMount } from 'svelte'
  import { getActions } from '../../utils/actions'


  let config: BulletLegendConfigInterface
  $: config = { items, ...$$restProps }

  // component declaration
  let component: BulletLegend
  let ref: HTMLDivElement
  const { setConfig } = getActions.apply({
    setConfig: (c: BulletLegendConfigInterface) => component?.update(c),
    render: () => component?.render()
  })
  // data and required props
  export let items: BulletLegendItemInterface[]
  onMount(() => {
    component = new BulletLegend(ref, config)
    return () => component.destroy()
  })

</script>

<vis-bullet-legend bind:this={ref} style:display='block' use:setConfig={config} />
