// packages/vue/src/components/area/index.vue
<script setup lang="ts" generic="Datum">
// !!! This code was automatically generated. You should not change it !!!
import { Area, AreaConfigInterface, NumericAccessor } from '@unovis/ts'
import { onMounted, onUnmounted, computed, ref, watch, getCurrentInstance, nextTick, inject } from 'vue'
import { arePropsEqual, parseProps } from '../../utils/props'
import { componentAccessorKey } from '../../utils/context'

const accessor = inject(componentAccessorKey)

// data and required props
const props = defineProps<AreaConfigInterface<Datum> & { data?: Datum[] }>()
const data = computed(() => accessor.data.value ?? props.data)
// config
const instance = getCurrentInstance()
const config = computed(() => parseProps({ ...props }, instance))

// component declaration
const component = ref<Area<Datum>>()


onMounted(() => {
  nextTick(() => {
    component.value = new Area<Datum>(config.value)
    component.value?.setData(data.value)
    accessor.update(component.value)
  })
})

onUnmounted(() => {
  component.value?.destroy()
  accessor.destroy()
})

watch(config, (curr, prev) => {
  if (!arePropsEqual(curr, prev)) {
    component.value?.setConfig(config.value)
  }
})

defineExpose({
  component
})
</script>

<template>
  <div data-vis-component />
</template>

// packages/svelte/src/components/area/area.svelte
<script lang="ts">
  // !!! This code was automatically generated. You should not change it !!!
  import { Area, AreaConfigInterface, NumericAccessor } from '@unovis/ts'
  import { onMount, getContext } from 'svelte'
  
  import type { Lifecycle } from '../../types/context'
  import { arePropsEqual } from '../../utils/props'
  // type defs
  type Datum = $$Generic
  
  // data and required props
  // eslint-disable-next-line no-undef-init
export let data: Datum[] = undefined
  export let x: NumericAccessor<Datum>
  export let y: NumericAccessor<Datum> | NumericAccessor<Datum>[]

  // config
  let prevConfig: AreaConfigInterface<Datum>
  let config: AreaConfigInterface<Datum>
  $: config = { x,  y, ...$$restProps }

  // component declaration
  let component: Area<Datum>
  const lifecycle = getContext<Lifecycle>('component')

  onMount(() => {
    component = new Area<Datum>(config)
    return () => component?.destroy()
    })
  $: component?.setData(data)
  $: if(!arePropsEqual(prevConfig, config)) {
    component?.setConfig(config)
    prevConfig = config
  }

  // component accessor
  export function getComponent (): Area<Datum> { return component }

</script>

<vis-component use:lifecycle={component}/>
