// packages/solid/src/html-components/rolling-pin-legend/index.tsx
// !!! This code was automatically generated. You should not change it !!!
import { RollingPinLegend } from "@unovis/ts/components/rolling-pin-legend";
import type { RollingPinLegendConfigInterface } from "@unovis/ts/components/rolling-pin-legend/config";
import { createSignal, onCleanup, createEffect, on, onMount } from 'solid-js'
import { arePropsEqual } from '../../utils/props'

export type VisRollingPinLegendProps = RollingPinLegendConfigInterface

export const VisRollingPinLegendSelectors = RollingPinLegend.selectors

export function VisRollingPinLegend(props: VisRollingPinLegendProps) {
  const [component, setComponent] = createSignal<RollingPinLegend>()
   
  const [ref, setRef] = createSignal<HTMLDivElement>()

  onMount(() => {
    const r = ref()
    if(r) setComponent(new RollingPinLegend(r, props));
    
    
  })

  onCleanup(() => {
    component()?.destroy()
    
  })

  createEffect(
    on(
      () => ({ ...props }),
      (curr, prev) => {
        if (!arePropsEqual(prev, curr)) {
          component()?.setConfig(curr)
          
        }
      },
      {
        defer: true
      }
    )
  )

  

  return <div data-vis-component ref={setRef} style={{ display:"block" }} />
}

// packages/vue/src/html-components/rolling-pin-legend/index.vue
<script setup lang="ts">
// !!! This code was automatically generated. You should not change it !!!

import type { RollingPinLegendConfigInterface } from '@unovis/ts/components/rolling-pin-legend/config'
import { RollingPinLegend } from '@unovis/ts/components/rolling-pin-legend'
import { computed, nextTick, onMounted, onUnmounted, ref, watch } from 'vue'
import { arePropsEqual, useForwardProps } from '../../utils/props'

// data and required props
type Props = RollingPinLegendConfigInterface
const props = defineProps<Props & { data?: null }>()

const data = computed(() => props.data)
// config
const config = useForwardProps(props)

// component declaration
const component = ref<RollingPinLegend>()
const elRef = ref<HTMLDivElement>()

onMounted(() => {
  nextTick(() => {
    if (elRef.value)
      component.value = new RollingPinLegend(elRef.value, config.value)
  })
})

onUnmounted(() => {
  component.value?.destroy()
})

watch(config, (curr, prev) => {
  if (!arePropsEqual(curr, prev)) {
    component.value?.setConfig(config.value)
    component.value?.render()
  }
})

defineExpose({
  component,
})
</script>

<script lang="ts">
export const VisRollingPinLegendSelectors = RollingPinLegend.selectors
</script>

<template>
  <div ref="elRef" data-vis-rolling-pin-legend />
</template>

<style>
  [data-vis-rolling-pin-legend] {
    display:block;
  }
</style>
