// packages/solid/src/components/tooltip/index.tsx
// !!! This code was automatically generated. You should not change it !!!
import type { TooltipConfigInterface } from "@unovis/ts";
import { Tooltip } from "@unovis/ts";
import { createSignal, onCleanup, createEffect, on, onMount } from 'solid-js'
import { arePropsEqual } from '../../utils/props'
import { useVisContainer } from "../../utils/context";

export type VisTooltipProps = TooltipConfigInterface

export const VisTooltipSelectors = Tooltip.selectors

export function VisTooltip(props: VisTooltipProps) {
  const [component, setComponent] = createSignal<Tooltip>()
  const config = props
   const ctx = useVisContainer();
  
  onMount(() => {
    setComponent(new Tooltip(config));
    
    ctx.update("tooltip", component);
  })

  onCleanup(() => {
    component()?.destroy()
    ctx.destroy("tooltip");
  })

  createEffect(
    on(
      () => ({ ...config }),
      (curr, prev) => {
        if (!arePropsEqual(prev, curr)) {
          component()?.setConfig(curr)
          ctx.dirty()
        }
      },
      {
        defer: true
      }
    )
  )

  

  return <div data-vis-tooltip  />
}

// packages/vue/src/components/tooltip/index.vue
<script setup lang="ts" >
// !!! This code was automatically generated. You should not change it !!!
import { Tooltip, TooltipConfigInterface } from '@unovis/ts'
import { onMounted, onUnmounted, computed, ref, watch, nextTick, inject } from 'vue'
import { arePropsEqual, useForwardProps } from '../../utils/props'
import { tooltipAccessorKey } from '../../utils/context'

const accessor = inject(tooltipAccessorKey)

// data and required props 
type Props = TooltipConfigInterface
const props = defineProps<Props & { data?: null }>()


// config
const config = useForwardProps(props)

// component declaration
const component = ref<Tooltip>()


onMounted(() => {
  nextTick(() => {
    component.value = new Tooltip(config.value)
    
    accessor.update(component.value)
  })
})

onUnmounted(() => {
  component.value?.destroy()
  accessor.destroy()
})

watch(config, (curr, prev) => {
  if (!arePropsEqual(curr, prev)) {
    component.value?.setConfig(config.value)
  }
})


defineExpose({
  component
})
</script>

<script lang="ts">
export const VisTooltipSelectors = Tooltip.selectors
</script>

<template>
  <div data-vis-tooltip />
</template>
