// packages/vis-svelte/src/components/tooltip/tooltip.svelte
<script lang="ts">
  // !!! This code was automatically generated. You should not change it !!!
  import { Tooltip, TooltipConfigInterface } from '@unovis/ts'
  import { getContext, onMount } from 'svelte'
  import { getActions } from '../../utils/actions'


  let config: TooltipConfigInterface
  $: config = { ...$$restProps }

  // component declaration
  const component = new Tooltip(config)
  const { setTooltip } = getContext('container')
  const { setConfig } = getActions.apply(component)

  onMount(() => {
    setTooltip(component)
    return () => setTooltip(undefined) as void
  })

  // component accessor
  export function getComponent (): Tooltip { return component }

</script>

<vis-tooltip use:setConfig={config} />

// packages/vue/src/components/tooltip/index.vue
<script setup lang="ts" >
// !!! This code was automatically generated. You should not change it !!!
import { Tooltip, TooltipConfigInterface } from '@unovis/ts'
import { onMounted, onUnmounted, computed, ref, watch, nextTick, inject } from 'vue'
import { arePropsEqual, useForwardProps } from '../../utils/props'
import { tooltipAccessorKey } from '../../utils/context'

const accessor = inject(tooltipAccessorKey)

// data and required props 
interface Props extends  TooltipConfigInterface { }
const props = defineProps<Props & { data?: null }>()


// config
const config = useForwardProps(props)

// component declaration
const component = ref<Tooltip>()


onMounted(() => {
  nextTick(() => {
    component.value = new Tooltip(config.value)
    
    accessor.update(component.value)
  })
})

onUnmounted(() => {
  component.value?.destroy()
  accessor.destroy()
})

watch(config, (curr, prev) => {
  if (!arePropsEqual(curr, prev)) {
    component.value?.setConfig(config.value)
  }
})


defineExpose({
  component
})
</script>

<template>
  <div data-vis-tooltip />
</template>
