// packages/shared/examples/dagre-graph/dagre-graph-solid.tsx
import { JSX } from 'solid-js'
import { GraphLayoutType, GraphNodeShape } from '@unovis/ts'
import { VisGraph, VisSingleContainer } from '@unovis/solid'

import { data, NodeDatum, LinkDatum } from './data'

const DagreGraph = (): JSX.Element => {
  const layoutType = GraphLayoutType.Dagre
  const nodeLabel = (n: NodeDatum) => n.label
  const nodeShape = (n: NodeDatum) => n.shape as GraphNodeShape
  const nodeStroke = (l: LinkDatum) => l.color
  const linkFlow = (l: LinkDatum) => l.active
  const linkStroke = (l: LinkDatum) => l.color

  return (
    <VisSingleContainer data={data} height='50dvh'>
      <VisGraph
        layoutType={layoutType}
        nodeLabel={nodeLabel}
        nodeShape={nodeShape}
        nodeStroke={nodeStroke}
        linkFlow={linkFlow}
        linkStroke={linkStroke}
        data={data}
        disableZoom
      />
    </VisSingleContainer>
  )
}

export default DagreGraph

// packages/website/src/examples/dagre-graph/dagre-graph.tsx
import React, { useCallback } from 'react'
import { VisSingleContainer, VisGraph } from '@unovis/react'
import { GraphLayoutType } from '@unovis/ts'

import { data, NodeDatum, LinkDatum } from './data'

export default function BasicGraph (): JSX.Element {
  return (
    <VisSingleContainer data={data} height={600}>
      <VisGraph<NodeDatum, LinkDatum>
        layoutType={GraphLayoutType.Dagre}
        nodeLabel={useCallback(n => n.label, [])}
        nodeShape={useCallback(n => n.shape, [])}
        nodeStroke={useCallback(l => l.color, [])}
        linkFlow={useCallback(l => l.active, [])}
        linkStroke={useCallback(l => l.color, [])}
        disableZoom={true}
      />
    </VisSingleContainer>
  )
}
