// packages/vis-svelte/src/components/crosshair/crosshair.svelte
<script lang="ts">
  // !!! This code was automatically generated. You should not change it !!!
  import { Crosshair, CrosshairConfigInterface, NumericAccessor } from '@unovis/ts'
  import { getContext, onMount } from 'svelte'
  import { getActions } from '../../utils/actions'

  // type defs
  type Datum = $$Generic

  let config: CrosshairConfigInterface<Datum>
  $: config = { x, y, ...$$restProps }

  // component declaration
  const component = new Crosshair<Datum>(config)
  const { setCrosshair } = getContext('container')
  const { setConfig, setData } = getActions.apply(component)
  // data and required props
  export let data: Datum[]
  export let x: NumericAccessor<Datum>
  export let y: NumericAccessor<Datum> | NumericAccessor<Datum>[]
  onMount(() => {
    setCrosshair(component)
    return () => setCrosshair(undefined) as void
  })

</script>

<vis-crosshair use:setData={data} use:setConfig={config} />

// packages/solid/src/components/crosshair/index.tsx
// !!! This code was automatically generated. You should not change it !!!
import { Crosshair } from "@unovis/ts/components/crosshair";
import type { CrosshairConfigInterface } from "@unovis/ts/components/crosshair/config";
import { createSignal, onCleanup, createEffect, on, onMount } from 'solid-js'
import { arePropsEqual } from '../../utils/props'
import { useVisContainer } from "../../utils/context";

export type VisCrosshairProps<Datum> = CrosshairConfigInterface<Datum>& {
  data?: Datum[];
};

export const VisCrosshairSelectors = Crosshair.selectors

export function VisCrosshair<Datum>(props: VisCrosshairProps<Datum>) {
  const [component, setComponent] = createSignal<Crosshair<Datum>>()
   const ctx = useVisContainer();
  
  onMount(() => {
    setComponent(new Crosshair<Datum>(props));
    if (props.data) component()?.setData(props.data)
    ctx.update("crosshair", component);
  })

  onCleanup(() => {
    component()?.destroy()
    ctx.destroy("crosshair");
  })

  createEffect(
    on(
      () => ({ ...props }),
      (curr, prev) => {
        if (!arePropsEqual(prev, curr)) {
          component()?.setConfig(curr)
          ctx.dirty()
        }
      },
      {
        defer: true
      }
    )
  )

  
  createEffect(
    on(
      () => props.data,
      (data) => {
        if (data) {
          component()?.setData(data)
          ctx.dirty()
        }
      },
      {
        defer: true
      }
    )
  );


  return <div data-vis-crosshair  />
}
