// packages/vue/src/components/graph/index.vue
<script setup lang="ts" generic="N extends GraphInputNode,L extends GraphInputLink">
// !!! This code was automatically generated. You should not change it !!!
import { Graph, GraphConfigInterface, GraphInputNode, GraphInputLink } from '@unovis/ts'
import { onMounted, onUnmounted, computed, ref, watch, nextTick, inject } from 'vue'
import { arePropsEqual, useForwardProps } from '../../utils/props'
import { componentAccessorKey } from '../../utils/context'

const accessor = inject(componentAccessorKey)

// data and required props 
interface Props extends  GraphConfigInterface<N, L> { }
const props = defineProps<Props & { data?: { nodes: N[]; links?: L[] } }>()

const data = computed(() => accessor.data.value ?? props.data)
// config
const config = useForwardProps(props)

// component declaration
const component = ref<Graph<N, L>>()


onMounted(() => {
  nextTick(() => {
    component.value = new Graph<N, L>(config.value)
    component.value?.setData(data.value)
    accessor.update(component.value)
  })
})

onUnmounted(() => {
  component.value?.destroy()
  accessor.destroy()
})

watch(config, (curr, prev) => {
  if (!arePropsEqual(curr, prev)) {
    component.value?.setConfig(config.value)
  }
})

watch(data, () => {
  component.value?.setData(data.value)
})

defineExpose({
  component
})
</script>

<template>
  <div data-vis-component />
</template>

// packages/vis-svelte/src/components/graph/graph.svelte
<script lang="ts">
  // !!! This code was automatically generated. You should not change it !!!
  import { Graph, GraphConfigInterface, GraphInputNode, GraphInputLink } from '@unovis/ts'
  import { getContext, onMount } from 'svelte'
  import { getActions } from '../../utils/actions'

  // type defs
  type N = $$Generic<GraphInputNode>
  type L = $$Generic<GraphInputLink>

  let config: GraphConfigInterface<N, L>
  $: config = { ...$$restProps }

  // component declaration
  const component = new Graph<N, L>(config)
  const { setComponent, removeComponent } = getContext('container')
  const { setConfig, setData } = getActions.apply(component)
  // data and required props
  export let data: { nodes: N[]; links?: L[] }
  onMount(() => {
    setComponent(component)
    return () => removeComponent(component) as void
  })

  // component accessor
  export function getComponent (): Graph<N, L> { return component }

</script>

<vis-component use:setData={data} use:setConfig={config} />
