// packages/vis-svelte/src/components/timeline/timeline.svelte
<script lang="ts">
  // !!! This code was automatically generated. You should not change it !!!
  import { Timeline, TimelineConfigInterface, NumericAccessor } from '@unovis/ts'
  import { getContext, onMount } from 'svelte'
  import { getActions } from '../../utils/actions'

  // type defs
  type Datum = $$Generic

  let config: TimelineConfigInterface<Datum>
  $: config = { x, y, ...$$restProps }

  // component declaration
  const component = new Timeline<Datum>(config)
  const { setComponent, removeComponent } = getContext('container')
  const { setConfig, setData } = getActions.apply(component)
  // data and required props
  export let data: Datum[]
  export let x: NumericAccessor<Datum>
  export let y: NumericAccessor<Datum> | NumericAccessor<Datum>[]
  onMount(() => {
    setComponent(component)
    return () => removeComponent(component) as void
  })

</script>

<vis-component use:setData={data} use:setConfig={config} />

// packages/solid/src/components/timeline/index.tsx
// !!! This code was automatically generated. You should not change it !!!
import { Timeline } from "@unovis/ts/components/timeline";
import type { TimelineConfigInterface } from "@unovis/ts/components/timeline/config";
import { createSignal, onCleanup, createEffect, on, onMount } from 'solid-js'
import { arePropsEqual } from '../../utils/props'
import { useVisContainer } from "../../utils/context";

export type VisTimelineProps<Datum> = TimelineConfigInterface<Datum>& {
  data?: Datum[];
};

export const VisTimelineSelectors = Timeline.selectors

export function VisTimeline<Datum>(props: VisTimelineProps<Datum>) {
  const [component, setComponent] = createSignal<Timeline<Datum>>()
   const ctx = useVisContainer();
  
  onMount(() => {
    setComponent(new Timeline<Datum>(props));
    if (props.data) component()?.setData(props.data)
    ctx.update("component", component);
  })

  onCleanup(() => {
    component()?.destroy()
    ctx.destroy("component");
  })

  createEffect(
    on(
      () => ({ ...props }),
      (curr, prev) => {
        if (!arePropsEqual(prev, curr)) {
          component()?.setConfig(curr)
          ctx.dirty()
        }
      },
      {
        defer: true
      }
    )
  )

  
  createEffect(
    on(
      () => props.data,
      (data) => {
        if (data) {
          component()?.setData(data)
          ctx.dirty()
        }
      },
      {
        defer: true
      }
    )
  );


  return <div data-vis-component  />
}
