// packages/solid/src/components/timeline/index.tsx
// !!! This code was automatically generated. You should not change it !!!
import { Timeline } from "@unovis/ts/components/timeline";
import type { TimelineConfigInterface } from "@unovis/ts/components/timeline/config";
import { createSignal, onCleanup, createEffect, on, onMount } from 'solid-js'
import { arePropsEqual } from '../../utils/props'
import { useVisContainer } from "../../utils/context";

export type VisTimelineProps<Datum> = TimelineConfigInterface<Datum>& {
  data?: Datum[];
};

export const VisTimelineSelectors = Timeline.selectors

export function VisTimeline<Datum>(props: VisTimelineProps<Datum>) {
  const [component, setComponent] = createSignal<Timeline<Datum>>()
   const ctx = useVisContainer();
  
  onMount(() => {
    setComponent(new Timeline<Datum>(props));
    if (props.data) component()?.setData(props.data)
    ctx.update("component", component);
  })

  onCleanup(() => {
    component()?.destroy()
    ctx.destroy("component");
  })

  createEffect(
    on(
      () => ({ ...props }),
      (curr, prev) => {
        if (!arePropsEqual(prev, curr)) {
          component()?.setConfig(curr)
          ctx.dirty()
        }
      },
      {
        defer: true
      }
    )
  )

  
  createEffect(
    on(
      () => props.data,
      (data) => {
        if (data) {
          component()?.setData(data)
          ctx.dirty()
        }
      },
      {
        defer: true
      }
    )
  );


  return <div data-vis-component  />
}

// packages/svelte/src/components/timeline/timeline.svelte
<script lang="ts">
  // !!! This code was automatically generated. You should not change it !!!
  import { Timeline } from '@unovis/ts/components/timeline'
  import type { TimelineConfigInterface } from '@unovis/ts/components/timeline/config'
  import type { NumericAccessor } from '@unovis/ts/types/accessor'
  import { onMount, getContext } from 'svelte'

  import type { Lifecycle } from '../../types/context'
  import { arePropsEqual } from '../../utils/props'
  // type defs
  type Datum = $$Generic

  // data and required props
  // eslint-disable-next-line no-undef-init
  export let data: Datum[] = undefined
  export let x: NumericAccessor<Datum>

  // config
  let prevConfig: TimelineConfigInterface<Datum>
  let config: TimelineConfigInterface<Datum>
  $: config = { x, ...$$restProps }

  // component declaration
  let component: Timeline<Datum>
  const lifecycle = getContext<Lifecycle>('component')

  onMount(() => {
    component = new Timeline<Datum>(config)
    return () => component?.destroy()
  })
  $: component?.setData(data)
  $: if (!arePropsEqual(prevConfig, config)) {
    component?.setConfig(config)
    prevConfig = config
  }

  // component accessor
  export function getComponent (): Timeline<Datum> { return component }

</script>

<vis-component use:lifecycle={component}/>
