// packages/vue/src/components/topojson-map/index.vue
<script setup lang="ts" generic="AreaDatum, PointDatum, LinkDatum">
// !!! This code was automatically generated. You should not change it !!!

import type { TopoJSONMapConfigInterface } from '@unovis/ts/components/topojson-map/config'
import { TopoJSONMap } from '@unovis/ts/components/topojson-map'
import { computed, inject, nextTick, onMounted, onUnmounted, ref, watch } from 'vue'
import { componentAccessorKey } from '../../utils/context'
import { arePropsEqual, useForwardProps } from '../../utils/props'

const props = defineProps<Props & { data?: { areas?: AreaDatum[], points?: PointDatum[], links?: LinkDatum[] } }>()

const accessor = inject(componentAccessorKey)

// data and required props
type Props = TopoJSONMapConfigInterface<AreaDatum, PointDatum, LinkDatum>
const data = computed(() => accessor.data.value ?? props.data)
// config
const config = useForwardProps(props)

// component declaration
const component = ref<TopoJSONMap<AreaDatum, PointDatum, LinkDatum>>()

onMounted(() => {
  nextTick(() => {
    component.value = new TopoJSONMap<AreaDatum, PointDatum, LinkDatum>(config.value)
    component.value?.setData(data.value)
    accessor.update(component.value)
  })
})

onUnmounted(() => {
  component.value?.destroy()
  accessor.destroy()
})

watch(config, (curr, prev) => {
  if (!arePropsEqual(curr, prev)) {
    component.value?.setConfig(config.value)
    component.value?.render()
  }
})

watch(data, () => {
  component.value?.setData(data.value)
})

defineExpose({
  component,
})
</script>

<script lang="ts">
export const VisTopoJSONMapSelectors = TopoJSONMap.selectors
</script>

<template>
  <div data-vis-component />
</template>

// packages/solid/src/components/topojson-map/index.tsx
// !!! This code was automatically generated. You should not change it !!!
import { TopoJSONMap } from "@unovis/ts/components/topojson-map";
import type { TopoJSONMapConfigInterface } from "@unovis/ts/components/topojson-map/config";
import { createSignal, onCleanup, createEffect, on, onMount } from 'solid-js'
import { arePropsEqual } from '../../utils/props'
import { useVisContainer } from "../../utils/context";

export type VisTopoJSONMapProps<AreaDatum, PointDatum, LinkDatum> = TopoJSONMapConfigInterface<AreaDatum, PointDatum, LinkDatum>& {
  data?: {areas?: AreaDatum[]; points?: PointDatum[]; links?: LinkDatum[]};
};

export const VisTopoJSONMapSelectors = TopoJSONMap.selectors

export function VisTopoJSONMap<AreaDatum, PointDatum, LinkDatum>(props: VisTopoJSONMapProps<AreaDatum, PointDatum, LinkDatum>) {
  const [component, setComponent] = createSignal<TopoJSONMap<AreaDatum, PointDatum, LinkDatum>>()
   const ctx = useVisContainer();
  
  onMount(() => {
    setComponent(new TopoJSONMap<AreaDatum, PointDatum, LinkDatum>(props));
    if (props.data) component()?.setData(props.data)
    ctx.update("component", component);
  })

  onCleanup(() => {
    component()?.destroy()
    ctx.destroy("component");
  })

  createEffect(
    on(
      () => ({ ...props }),
      (curr, prev) => {
        if (!arePropsEqual(prev, curr)) {
          component()?.setConfig(curr)
          ctx.dirty()
        }
      },
      {
        defer: true
      }
    )
  )

  
  createEffect(
    on(
      () => props.data,
      (data) => {
        if (data) {
          component()?.setData(data)
          ctx.dirty()
        }
      },
      {
        defer: true
      }
    )
  );


  return <div data-vis-component  />
}
