// packages/svelte/src/components/chord-diagram/chord-diagram.svelte
<script lang="ts">
  // !!! This code was automatically generated. You should not change it !!!
  import { ChordDiagram } from '@unovis/ts/components/chord-diagram'
  import type { ChordDiagramConfigInterface } from '@unovis/ts/components/chord-diagram/config'
  import type { ChordInputNode, ChordInputLink } from '@unovis/ts/components/chord-diagram/types'
  import { onMount, getContext } from 'svelte'

  import type { Lifecycle } from '../../types/context'
  import { arePropsEqual } from '../../utils/props'
  // type defs
  type N = $$Generic<ChordInputNode>
  type L = $$Generic<ChordInputLink>

  // data and required props
  // eslint-disable-next-line no-undef-init
  export let data: { nodes: N[]; links?: L[] } = undefined

  // config
  let prevConfig: ChordDiagramConfigInterface<N, L>
  let config: ChordDiagramConfigInterface<N, L>
  $: config = { ...$$restProps }

  // component declaration
  let component: ChordDiagram<N, L>
  const lifecycle = getContext<Lifecycle>('component')

  onMount(() => {
    component = new ChordDiagram<N, L>(config)
    return () => component?.destroy()
  })
  $: component?.setData(data)
  $: if (!arePropsEqual(prevConfig, config)) {
    component?.setConfig(config)
    prevConfig = config
  }

  // component accessor
  export function getComponent (): ChordDiagram<N, L> { return component }

</script>

<vis-component use:lifecycle={component}/>

// packages/vue/src/components/chord-diagram/index.vue
<script setup lang="ts" generic="N extends ChordInputNode, L extends ChordInputLink">
// !!! This code was automatically generated. You should not change it !!!

import type { ChordDiagramConfigInterface } from '@unovis/ts/components/chord-diagram/config'
import type { ChordInputLink, ChordInputNode } from '@unovis/ts/components/chord-diagram/types'
import { ChordDiagram } from '@unovis/ts/components/chord-diagram'
import { computed, inject, nextTick, onMounted, onUnmounted, ref, watch } from 'vue'
import { componentAccessorKey } from '../../utils/context'
import { arePropsEqual, useForwardProps } from '../../utils/props'

const props = defineProps<Props & { data?: { nodes: N[], links?: L[] } }>()

const accessor = inject(componentAccessorKey)

// data and required props
type Props = ChordDiagramConfigInterface<N, L>
const data = computed(() => accessor.data.value ?? props.data)
// config
const config = useForwardProps(props)

// component declaration
const component = ref<ChordDiagram<N, L>>()

onMounted(() => {
  nextTick(() => {
    component.value = new ChordDiagram<N, L>(config.value)
    component.value?.setData(data.value)
    accessor.update(component.value)
  })
})

onUnmounted(() => {
  component.value?.destroy()
  accessor.destroy()
})

watch(config, (curr, prev) => {
  if (!arePropsEqual(curr, prev)) {
    component.value?.setConfig(config.value)
    component.value?.render()
  }
})

watch(data, () => {
  component.value?.setData(data.value)
})

defineExpose({
  component,
})
</script>

<script lang="ts">
export const VisChordDiagramSelectors = ChordDiagram.selectors
</script>

<template>
  <div data-vis-component />
</template>
