// packages/website/src/examples/multi-line-chart/multi-line-chart.tsx
import React, { useCallback } from 'react'
import { VisXYContainer, VisLine, VisAxis, VisBulletLegend } from '@volterra/vis-react'

import { data, labels, CityTemps } from './data'

export default function MultiLineChart (): JSX.Element {
  const legendItems = ['austin', 'ny', 'sf'].map(city => ({ name: labels[city] }))
  return (
    <VisXYContainer data={data} height={300}>
      <VisLine
        x={useCallback((d: CityTemps) => new Date(d.date), [])}
        y={[
          useCallback((d: CityTemps) => d.austin, []),
          useCallback((d: CityTemps) => d.ny, []),
          useCallback((d: CityTemps) => d.sf, []),
        ]}/>
      <VisAxis type="x" label="Date" numTicks={6} tickFormat={Intl.DateTimeFormat().format}/>
      <VisAxis type="y" label="Temperature (celsius)"/>
      <VisBulletLegend items={legendItems}/>
    </VisXYContainer>
  )
}

// packages/website/src/examples/multi-line-chart/multi-line-chart.svelte
<script lang='ts'>
  import { VisXYContainer, VisLine, VisAxis, VisBulletLegend } from '@volterra/vis-svelte'
  import { data, labels, CityTemps } from './data'

  const x= (d: CityTemps) => +(new Date(d.date))
  const y = [
    (d: CityTemps) => d.austin,
    (d: CityTemps) => d.ny,
    (d: CityTemps) => d.sf,
  ]
  const items = ['austin', 'ny', 'sf'].map(city => ({ name: labels[city] }))
</script>
<VisXYContainer data={data} height={300}>
  <VisLine {x} {y}/>
  <VisAxis type="x" label="Date" numTicks={6} tickFormat={Intl.DateTimeFormat().format}/>
  <VisAxis type="y" label="Temperature (celsius)"/>
  <VisBulletLegend {items}/>
</VisXYContainer>
