// packages/react/src/components/plotband/index.tsx
// !!! This code was automatically generated. You should not change it !!!
import React, { ForwardedRef, ReactElement, Ref, useImperativeHandle, useEffect, useRef, useState } from 'react'
import { Plotband } from '@unovis/ts/components/plotband'
import { PlotbandConfigInterface } from '@unovis/ts/components/plotband/config'

// Utils
import { arePropsEqual } from 'src/utils/react'

// Types
import { VisComponentElement } from 'src/types/dom'

export type VisPlotbandRef<Datum> = {
  component?: Plotband<Datum>;
}

export type VisPlotbandProps<Datum> = PlotbandConfigInterface<Datum> & {
  ref?: Ref<VisPlotbandRef<Datum>>;
}

export const VisPlotbandSelectors = Plotband.selectors

// eslint-disable-next-line @typescript-eslint/naming-convention
function VisPlotbandFC<Datum> (props: VisPlotbandProps<Datum>, fRef: ForwardedRef<VisPlotbandRef<Datum>>): ReactElement {
  const ref = useRef<VisComponentElement<Plotband<Datum>>>(null)
  const componentRef = useRef<Plotband<Datum> | undefined>(undefined)

  // On Mount
  useEffect(() => {
    const element = (ref.current as VisComponentElement<Plotband<Datum>>)

    const c = new Plotband<Datum>(props)
    componentRef.current = c
    element.__component__ = c

    return () => {
      componentRef.current = undefined
      c.destroy()
    }
  }, [])

  // On Props Update
  useEffect(() => {
    const component = componentRef.current

    component?.setConfig(props)
  })

  useImperativeHandle(fRef, () => ({ get component () { return componentRef.current } }), [])
  return <vis-component ref={ref} />
}

// We export a memoized component to avoid unnecessary re-renders
//  and define its type explicitly to help react-docgen-typescript to extract information about props
export const VisPlotband: (<Datum>(props: VisPlotbandProps<Datum>) => JSX.Element | null) = React.memo(React.forwardRef(VisPlotbandFC), arePropsEqual)

// packages/solid/src/components/plotband/index.tsx
// !!! This code was automatically generated. You should not change it !!!
import { Plotband } from "@unovis/ts/components/plotband";
import type { PlotbandConfigInterface } from "@unovis/ts/components/plotband/config";
import { createSignal, onCleanup, createEffect, on, onMount } from 'solid-js'
import { arePropsEqual } from '../../utils/props'
import { useVisContainer } from "../../utils/context";

export type VisPlotbandProps<Datum> = PlotbandConfigInterface<Datum>

export const VisPlotbandSelectors = Plotband.selectors

export function VisPlotband<Datum>(props: VisPlotbandProps<Datum>) {
  const [component, setComponent] = createSignal<Plotband<Datum>>()
   const ctx = useVisContainer();
  
  onMount(() => {
    setComponent(new Plotband<Datum>(props));
    
    ctx.update("component", component);
  })

  onCleanup(() => {
    component()?.destroy()
    ctx.destroy("component");
  })

  createEffect(
    on(
      () => ({ ...props }),
      (curr, prev) => {
        if (!arePropsEqual(prev, curr)) {
          component()?.setConfig(curr)
          ctx.dirty()
        }
      },
      {
        defer: true
      }
    )
  )

  

  return <div data-vis-component  />
}
