// packages/website/src/examples/step-area-chart/step-area-chart.component.ts
import { Component } from '@angular/core'
import { BulletLegendItemInterface, CurveType } from '@unovis/ts'
import { candidates, data, DataRecord } from './data'

@Component({
  selector: 'step-area-chart',
  templateUrl: './step-area-chart.component.html',
  styleUrls: ['./styles.css'],
})
export class StepAreaChartComponent {
  candidates: BulletLegendItemInterface[]
  curveType = CurveType.StepAfter
  data = data
  legendItems = Object.keys(data[0][candidates[0].name]).map(c => ({ name: c as string }))
  x = (d: DataRecord): number => d.year
  y: ((d: DataRecord) => number)[]

  constructor () {
    this.setCandidate(candidates[0])
  }

  setCandidate = (candidate: BulletLegendItemInterface): void => {
    this.candidates = candidates.map(c => ({ ...c, inactive: candidate.name !== c.name }))
    this.y = this.legendItems.map(i => (d: DataRecord) => d[candidate.name][i.name])
  }
}

<div class="panel">
  <vis-bullet-legend [items]="legendItems"></vis-bullet-legend>
  <div class="legendSwitch">
    <vis-bullet-legend [items]="candidates" [onLegendItemClick]="setCandidate"></vis-bullet-legend>
  </div>
</div>

<vis-xy-container [data]="data" [height]="400" [yDomain]="[0, 42]">
    <vis-area [x]="x" [y]="y" [curveType]="curveType"></vis-area>
    <vis-axis type="x" label="Year"></vis-axis>
    <vis-axis type="y" label="Number of Mentions"></vis-axis>
</vis-xy-container>

// packages/shared/examples/step-area-chart/step-area-chart-solid.tsx
import { createMemo, createSignal, JSX } from 'solid-js'
import { VisArea, VisAxis, VisBulletLegend, VisXYContainer } from '@unovis/solid'
import { BulletLegendItemInterface, CurveType } from '@unovis/ts'

import './styles.css'

import { data, candidates, DataRecord } from './data'

const StepAreaChart = (): JSX.Element => {
  const [curr, setCurr] = createSignal(candidates[0].name)

  const keys = createMemo(() =>
    Object.keys(data[0][curr()]).map((d) => ({ name: d }))
  )
  const x = (d: DataRecord) => d.year

  function onLegendItemClick (i: BulletLegendItemInterface): void {
    setCurr(i.name as string)
  }

  const y = createMemo(() =>
    keys().map((i) => (d: DataRecord) => d[curr()][i.name])
  )
  const items = createMemo(() =>
    candidates.map((c) => ({ ...c, inactive: curr() !== c.name }))
  )

  return (
    <div class='step-area-chart'>
      <div class='panel'>
        <VisBulletLegend
          items={Object.keys(data[0][curr()]).map((d) => ({ name: d }))}
        />
        <div class='legendSwitch'>
          <VisBulletLegend
            labelClassName='legendLabel'
            items={items()}
            onLegendItemClick={onLegendItemClick}
          />
        </div>
      </div>
      <VisXYContainer data={data} height='50dvh' yDomain={[0, 42]}>
        <VisArea x={x} y={y()} curveType={CurveType.StepAfter} />
        <VisAxis type='x' label='Year' />
        <VisAxis type='y' label='Number of Mentions' />
      </VisXYContainer>
    </div>
  )
}

export default StepAreaChart
