// packages/shared/examples/basic-plotline/basic-plotline.tsx
import { VisAxis, VisLine, VisPlotline, VisXYContainer } from '@unovis/react'
import React, { useCallback } from 'react'
import { data } from './data'


export default function BasicPlotlineChart (): JSX.Element {
  return (
    <VisXYContainer height={'50vh'}>
      <VisLine
        data={data}
        x={useCallback(d => d.x, [])}
        y={useCallback(d => d.y, [])}
      ></VisLine>
      <VisAxis type="x"></VisAxis>
      <VisAxis type="y"></VisAxis>
      <VisPlotline value={1} color="red"></VisPlotline>
    </VisXYContainer>
  )
}

// packages/shared/examples/basic-plotline/basic-plotline-solid.tsx
import { VisAxis, VisLine, VisPlotline, VisXYContainer } from '@unovis/solid'
import { JSX } from 'solid-js'
import { data } from './data'

const BasicPlotlineChart = (): JSX.Element => {
  return (
    <VisXYContainer height='50dvh'>
      <VisLine data={data} x={(d) => d.x} y={(d) => d.y} />
      <VisAxis type='x' />
      <VisAxis type='y' />
      <VisPlotline value={1} color='red'></VisPlotline>
    </VisXYContainer>
  )
}

export default BasicPlotlineChart
