// packages/svelte/src/components/crosshair/crosshair.svelte
<script lang="ts">
  // !!! This code was automatically generated. You should not change it !!!
  import { Crosshair, CrosshairConfigInterface } from '@unovis/ts'
  import { getContext, onMount } from 'svelte'
  import { arePropsEqual } from '../../utils/props'

  // type defs
  type Datum = $$Generic

  // data and required props
  // eslint-disable-next-line no-undef-init
  export let data: Datum[] = undefined

  // config
  let prevConfig: CrosshairConfigInterface<Datum>
  let config: CrosshairConfigInterface<Datum>
  $: config = { ...$$restProps }

  // component declaration
  let component: Crosshair<Datum>
  const { setCrosshair } = getContext('container')

  onMount(() => {
    component = new Crosshair<Datum>(config)
    setCrosshair(component)
    return () => { setCrosshair(undefined) as void }
  })

  $: component?.setData(data)
  $: if (!arePropsEqual(prevConfig, config)) {
    component?.setConfig(config)
    prevConfig = config
  }

  // component accessor
  export function getComponent (): Crosshair<Datum> { return component }

</script>

<vis-crosshair/>

// packages/vis-react/src/components/crosshair/index.tsx
/* eslint-disable notice/notice */
// !!! This code was automatically generated. You should not change it !!!
import { useEffect, useRef, useState } from 'react'
// import { Crosshair, CrosshairConfigInterface } from '@volterra/vis'
import { Crosshair, CrosshairConfigInterface, GenericDataRecord } from '@volterra/vis'

export type VisCrosshairProps<Datum = GenericDataRecord> = CrosshairConfigInterface<Datum> & { data?: Datum[] }

// eslint-disable-next-line @typescript-eslint/naming-convention
export function VisCrosshair<Datum = GenericDataRecord> (props: VisCrosshairProps<Datum>): JSX.Element {
  // eslint-disable-next-line @typescript-eslint/naming-convention
  type RefType = HTMLDivElement & { __component__: Crosshair<Datum> }
  const ref = useRef<RefType>(null)
  const [component] = useState<Crosshair<Datum>>(new Crosshair(props))

  // On Mount
  useEffect(() => {
    (ref.current as RefType).__component__ = component
  }, [])

  // On Props Update
  useEffect(() => {
    component?.setData(props.data ?? [])
    component?.setConfig(props)
  })

  return <vis-component ref={ref} />
}
