// packages/vue/src/components/circular-bar/index.vue
<script setup lang="ts" generic="Datum">
// !!! This code was automatically generated. You should not change it !!!
import type { CircularBarConfigInterface } from '@unovis/ts'
import { CircularBar } from '@unovis/ts'
import { computed, inject, nextTick, onMounted, onUnmounted, ref, watch } from 'vue'
import { componentAccessorKey } from '../../utils/context'
import { arePropsEqual, useForwardProps } from '../../utils/props'

const props = defineProps<Props & { data?: Datum[] }>()

const accessor = inject(componentAccessorKey)

// data and required props
type Props = CircularBarConfigInterface<Datum>
const data = computed(() => accessor.data.value ?? props.data)
// config
const config = useForwardProps(props)

// component declaration
const component = ref<CircularBar<Datum>>()

onMounted(() => {
  nextTick(() => {
    component.value = new CircularBar<Datum>(config.value)
    component.value?.setData(data.value)
    accessor.update(component.value)
  })
})

onUnmounted(() => {
  component.value?.destroy()
  accessor.destroy()
})

watch(config, (curr, prev) => {
  if (!arePropsEqual(curr, prev)) {
    component.value?.setConfig(config.value)
    component.value?.render()
  }
})

watch(data, () => {
  component.value?.setData(data.value)
})

defineExpose({
  component,
})
</script>

<script lang="ts">
export const VisCircularBarSelectors = CircularBar.selectors
</script>

<template>
  <div data-vis-component />
</template>

// packages/solid/src/components/circular-bar/index.tsx
// !!! This code was automatically generated. You should not change it !!!
import type { CircularBarConfigInterface } from "@unovis/ts";
import { CircularBar } from "@unovis/ts";
import { createSignal, onCleanup, createEffect, on, onMount } from 'solid-js'
import { arePropsEqual } from '../../utils/props'
import { useVisContainer } from "../../utils/context";

export type VisCircularBarProps<Datum> = CircularBarConfigInterface<Datum>& {
  data?: Datum[];
};

export const VisCircularBarSelectors = CircularBar.selectors

export function VisCircularBar<Datum>(props: VisCircularBarProps<Datum>) {
  const [component, setComponent] = createSignal<CircularBar<Datum>>()
   const ctx = useVisContainer();
  
  onMount(() => {
    setComponent(new CircularBar<Datum>(props));
    if (props.data) component()?.setData(props.data)
    ctx.update("component", component);
  })

  onCleanup(() => {
    component()?.destroy()
    ctx.destroy("component");
  })

  createEffect(
    on(
      () => ({ ...props }),
      (curr, prev) => {
        if (!arePropsEqual(prev, curr)) {
          component()?.setConfig(curr)
          ctx.dirty()
        }
      },
      {
        defer: true
      }
    )
  )

  
  createEffect(
    on(
      () => props.data,
      (data) => {
        if (data) {
          component()?.setData(data)
          ctx.dirty()
        }
      },
      {
        defer: true
      }
    )
  );


  return <div data-vis-component  />
}
