// packages/vue/src/html-components/rolling-pin-legend/index.vue
<script setup lang="ts" >
// !!! This code was automatically generated. You should not change it !!!
import { RollingPinLegend, RollingPinLegendConfigInterface, RollingPinLegendItem } from '@unovis/ts'
import { onMounted, onUnmounted, computed, ref, watch, nextTick } from 'vue'
import { arePropsEqual, useForwardProps } from '../../utils/props'


// data and required props 
type Props = RollingPinLegendConfigInterface
const props = defineProps<Props & { data?: null }>()

const data = computed(() => props.data)
// config
const config = useForwardProps(props)

// component declaration
const component = ref<RollingPinLegend>()
const elRef = ref<HTMLDivElement>()

onMounted(() => {
  nextTick(() => {
    if(elRef.value)
    component.value = new RollingPinLegend(elRef.value, config.value)
    
    
  })
})

onUnmounted(() => {
  component.value?.destroy()
  
})

watch(config, (curr, prev) => {
  if (!arePropsEqual(curr, prev)) {
    component.value?.setConfig(config.value)
  }
})


defineExpose({
  component
})
</script>

<script lang="ts">
export const VisRollingPinLegendSelectors = RollingPinLegend.selectors
</script>

<template>
  <div data-vis-rolling-pin-legend ref="elRef"/>
</template>


<style>
  [data-vis-rolling-pin-legend] {
    display:block;
  }
</style>

// packages/svelte/src/html-components/rolling-pin-legend/rolling-pin-legend.svelte
<script lang="ts">
  // !!! This code was automatically generated. You should not change it !!!
  import { RollingPinLegend, type RollingPinLegendConfigInterface, type RollingPinLegendItem } from '@unovis/ts'
  import { onMount } from 'svelte'

  import { arePropsEqual } from '../../utils/props'


  // data and required props
  // eslint-disable-next-line no-undef-init
  export let rects: RollingPinLegendItem[]

  // config
  let prevConfig: RollingPinLegendConfigInterface
  let config: RollingPinLegendConfigInterface
  $: config = { rects, ...$$restProps }

  // component declaration
  let component: RollingPinLegend
  let ref: HTMLDivElement

  onMount(() => {
    component = new RollingPinLegend(ref, config)
    return () => component?.destroy()
  })
  $: if (!arePropsEqual(prevConfig, config)) {
    component?.setConfig(config)
    prevConfig = config
  }

  // component accessor
  export function getComponent (): RollingPinLegend { return component }

</script>

<vis-rolling-pin-legend bind:this={ref}></vis-rolling-pin-legend>

<style>
  vis-rolling-pin-legend {
    display:block;
  }
</style>
