// packages/svelte/src/components/sankey/sankey.svelte
<script lang="ts">
  // !!! This code was automatically generated. You should not change it !!!
  import { Sankey, SankeyConfigInterface, SankeyInputNode, SankeyInputLink } from '@unovis/ts'
  import { onMount, getContext } from 'svelte'
  
  import type { Lifecycle } from '../../types/context'
  import { arePropsEqual } from '../../utils/props'
  // type defs
  type N = $$Generic<SankeyInputNode>
  type L = $$Generic<SankeyInputLink>
  
  // data and required props
  // eslint-disable-next-line no-undef-init
export let data: { nodes: N[]; links?: L[] } = undefined

  // config
  let prevConfig: SankeyConfigInterface<N, L>
  let config: SankeyConfigInterface<N, L>
  $: config = { ...$$restProps }

  // component declaration
  let component: Sankey<N, L>
  const lifecycle = getContext<Lifecycle>('component')

  onMount(() => {
    component = new Sankey<N, L>(config)
    return () => component?.destroy()
    })
  $: component?.setData(data)
  $: if(!arePropsEqual(prevConfig, config)) {
    component?.setConfig(config)
    prevConfig = config
  }

  // component accessor
  export function getComponent (): Sankey<N, L> { return component }

</script>

<vis-component use:lifecycle={component}/>

// packages/vis-react/src/components/sankey/index.tsx
/* eslint-disable notice/notice */
// !!! This code was automatically generated. You should not change it !!!
import { useEffect, useRef, useState } from 'react'
// import { Sankey, SankeyConfigInterface } from '@volterra/vis'
import { Sankey, SankeyConfigInterface, SankeyInputNode, SankeyInputLink } from '@volterra/vis'

// Types
import { VisComponentElement } from 'src/types/dom'

export type VisSankeyProps<N extends SankeyInputNode = SankeyInputNode, L extends SankeyInputLink = SankeyInputLink> = SankeyConfigInterface<N, L> & { data?: any }

// eslint-disable-next-line @typescript-eslint/naming-convention
export function VisSankey<N extends SankeyInputNode = SankeyInputNode, L extends SankeyInputLink = SankeyInputLink> (props: VisSankeyProps<N, L>): JSX.Element {
  const ref = useRef<VisComponentElement<Sankey<N, L>>>(null)
  const [component] = useState<Sankey<N, L>>(new Sankey(props))

  // On Mount
  useEffect(() => {
    (ref.current as VisComponentElement<Sankey<N, L>>).__component__ = component
  }, [])

  // On Props Update
  useEffect(() => {
    component?.setData(props.data ?? [])
    component?.setConfig(props)
  })

  return <vis-component ref={ref} />
}
