// packages/svelte/src/html-components/flow-legend/flow-legend.svelte
<script lang="ts">
  // !!! This code was automatically generated. You should not change it !!!
  import { FlowLegend } from '@unovis/ts/components/flow-legend'
  import type { FlowLegendConfigInterface } from '@unovis/ts/components/flow-legend/config'
  import { onMount } from 'svelte'

  import { arePropsEqual } from '../../utils/props'


  // config
  let prevConfig: FlowLegendConfigInterface
  let config: FlowLegendConfigInterface
  $: config = { ...$$restProps }

  // component declaration
  let component: FlowLegend
  let ref: HTMLDivElement

  onMount(() => {
    component = new FlowLegend(ref, { ...config, renderIntoProvidedDomNode: true })
    return () => component?.destroy()
  })
  $: if (!arePropsEqual(prevConfig, config)) {
    component?.setConfig(config)
    prevConfig = config
  }

  // component accessor
  export function getComponent (): FlowLegend { return component }

</script>

<vis-flow-legend bind:this={ref}/>

<style>
  vis-flow-legend {
    display:block;
  }
</style>

// packages/solid/src/html-components/flow-legend/index.tsx
// !!! This code was automatically generated. You should not change it !!!
import { FlowLegend } from "@unovis/ts/components/flow-legend";
import type { FlowLegendConfigInterface } from "@unovis/ts/components/flow-legend/config";
import { createSignal, onCleanup, createEffect, on, onMount } from 'solid-js'
import { arePropsEqual } from '../../utils/props'

export type VisFlowLegendProps = FlowLegendConfigInterface

export const VisFlowLegendSelectors = FlowLegend.selectors

export function VisFlowLegend(props: VisFlowLegendProps) {
  const [component, setComponent] = createSignal<FlowLegend>()
   
  const [ref, setRef] = createSignal<HTMLDivElement>()

  onMount(() => {
    const r = ref()
    if(r) setComponent(new FlowLegend(r, { ...props, renderIntoProvidedDomNode: true }));
    
    
  })

  onCleanup(() => {
    component()?.destroy()
    
  })

  createEffect(
    on(
      () => ({ ...props }),
      (curr, prev) => {
        if (!arePropsEqual(prev, curr)) {
          component()?.setConfig(curr)
          
        }
      },
      {
        defer: true
      }
    )
  )

  

  return <div data-vis-component ref={setRef} style={{ display:"block" }} />
}
