// packages/vue/src/html-components/flow-legend/index.vue
<script setup lang="ts">
// !!! This code was automatically generated. You should not change it !!!

import type { FlowLegendConfigInterface } from '@unovis/ts/components/flow-legend/config'
import { FlowLegend } from '@unovis/ts/components/flow-legend'
import { computed, nextTick, onMounted, onUnmounted, ref, watch } from 'vue'
import { arePropsEqual, useForwardProps } from '../../utils/props'

// data and required props
type Props = FlowLegendConfigInterface
const props = defineProps<Props & { data?: null }>()

const data = computed(() => props.data)
// config
const config = useForwardProps(props)

// component declaration
const component = ref<FlowLegend>()
const elRef = ref<HTMLDivElement>()

onMounted(() => {
  nextTick(() => {
    if (elRef.value)
      component.value = new FlowLegend(elRef.value, { ...config.value, renderIntoProvidedDomNode: true })
  })
})

onUnmounted(() => {
  component.value?.destroy()
})

watch(config, (curr, prev) => {
  if (!arePropsEqual(curr, prev)) {
    component.value?.setConfig(config.value)
    component.value?.render()
  }
})

defineExpose({
  component,
})
</script>

<script lang="ts">
export const VisFlowLegendSelectors = FlowLegend.selectors
</script>

<template>
  <div ref="elRef" data-vis-flow-legend />
</template>

<style>
  [data-vis-flow-legend] {
    display:block;
  }
</style>

// packages/solid/src/html-components/flow-legend/index.tsx
// !!! This code was automatically generated. You should not change it !!!
import { FlowLegend } from "@unovis/ts/components/flow-legend";
import type { FlowLegendConfigInterface } from "@unovis/ts/components/flow-legend/config";
import { createSignal, onCleanup, createEffect, on, onMount } from 'solid-js'
import { arePropsEqual } from '../../utils/props'

export type VisFlowLegendProps = FlowLegendConfigInterface

export const VisFlowLegendSelectors = FlowLegend.selectors

export function VisFlowLegend(props: VisFlowLegendProps) {
  const [component, setComponent] = createSignal<FlowLegend>()
   
  const [ref, setRef] = createSignal<HTMLDivElement>()

  onMount(() => {
    const r = ref()
    if(r) setComponent(new FlowLegend(r, { ...props, renderIntoProvidedDomNode: true }));
    
    
  })

  onCleanup(() => {
    component()?.destroy()
    
  })

  createEffect(
    on(
      () => ({ ...props }),
      (curr, prev) => {
        if (!arePropsEqual(prev, curr)) {
          component()?.setConfig(curr)
          
        }
      },
      {
        defer: true
      }
    )
  )

  

  return <div data-vis-component ref={setRef} style={{ display:"block" }} />
}
