// packages/shared/examples/basic-boxplot/basic-boxplot.tsx
import React, { useCallback } from 'react'
import { VisXYContainer, VisBoxplot, VisAxis } from '@unovis/react'

import { data, DataRecord } from './data'

export default function BasicBoxplot (): JSX.Element {
  return (
    <VisXYContainer height={'50vh'}>
      <VisBoxplot
        data={data}
        x={useCallback((d: DataRecord) => d.x, [])}
        median={useCallback((d: DataRecord) => d.median, [])}
        quartiles={useCallback((d: DataRecord) => d.quartiles, [])}
        whiskers={useCallback((d: DataRecord) => d.whiskers, [])}
      ></VisBoxplot>
      <VisAxis type="x"></VisAxis>
      <VisAxis type="y"></VisAxis>
    </VisXYContainer>
  )
}

// packages/shared/examples/basic-boxplot/basic-boxplot-solid.tsx
import { JSX } from 'solid-js'
import { VisAxis, VisBoxplot, VisXYContainer } from '@unovis/solid'

import { data } from './data'

const BasicBoxplot = (): JSX.Element => {
  return (
    <VisXYContainer height='50dvh'>
      <VisBoxplot
        data={data}
        x={(d) => d.x}
        median={(d) => d.median}
        quartiles={(d) => d.quartiles}
        whiskers={(d) => d.whiskers}
      />
      <VisAxis type='x' />
      <VisAxis type='y' />
    </VisXYContainer>
  )
}

export default BasicBoxplot
