// packages/vue/src/components/treemap/index.vue
<script setup lang="ts" generic="Datum">
// !!! This code was automatically generated. You should not change it !!!
import { Treemap, TreemapConfigInterface, StringAccessor } from '@unovis/ts'
import { onMounted, onUnmounted, computed, ref, watch, nextTick, inject } from 'vue'
import { arePropsEqual, useForwardProps } from '../../utils/props'
import { componentAccessorKey } from '../../utils/context'

const accessor = inject(componentAccessorKey)

// data and required props 
type Props = TreemapConfigInterface<Datum>
const props = defineProps<Props & { data?: Datum[] }>()

const data = computed(() => accessor.data.value ?? props.data)
// config
const config = useForwardProps(props)

// component declaration
const component = ref<Treemap<Datum>>()


onMounted(() => {
  nextTick(() => {
    component.value = new Treemap<Datum>(config.value)
    component.value?.setData(data.value)
    accessor.update(component.value)
  })
})

onUnmounted(() => {
  component.value?.destroy()
  accessor.destroy()
})

watch(config, (curr, prev) => {
  if (!arePropsEqual(curr, prev)) {
    component.value?.setConfig(config.value)
  }
})

watch(data, () => {
  component.value?.setData(data.value)
})

defineExpose({
  component
})
</script>

<script lang="ts">
export const VisTreemapSelectors = Treemap.selectors
</script>

<template>
  <div data-vis-component />
</template>

// packages/svelte/src/components/treemap/treemap.svelte
<script lang="ts">
  // !!! This code was automatically generated. You should not change it !!!
  import { Treemap, TreemapConfigInterface, StringAccessor } from '@unovis/ts'
  import { onMount, getContext } from 'svelte'

  import type { Lifecycle } from '../../types/context'
  import { arePropsEqual } from '../../utils/props'
  // type defs
  type Datum = $$Generic

  // data and required props
  // eslint-disable-next-line no-undef-init
  export let data: Datum[] = undefined
  export let layers: StringAccessor<Datum>[]

  // config
  let prevConfig: TreemapConfigInterface<Datum>
  let config: TreemapConfigInterface<Datum>
  $: config = { layers, ...$$restProps }

  // component declaration
  let component: Treemap<Datum>
  const lifecycle = getContext<Lifecycle>('component')

  onMount(() => {
    component = new Treemap<Datum>(config)
    return () => component?.destroy()
  })
  $: component?.setData(data)
  $: if (!arePropsEqual(prevConfig, config)) {
    component?.setConfig(config)
    prevConfig = config
  }

  // component accessor
  export function getComponent (): Treemap<Datum> { return component }

</script>

<vis-component use:lifecycle={component}></vis-component>
