// packages/shared/examples/topojson-map/topojson-map.tsx
import React, { useCallback, useMemo, useState } from 'react'
import { ScaleSequential } from 'd3-scale'
import { Orientation, Scale, TopoJSONMap } from '@unovis/ts'
import { WorldMapTopoJSON } from '@unovis/ts/maps'
import { VisSingleContainer, VisTopoJSONMap, VisTooltip, VisAxis, VisXYContainer, VisStackedBar } from '@unovis/react'
import { palette, data, ageRange, yearRange, AreaDatum } from './data'

import './styles.css'

type YearSliderProps = {
  current: number;
  range: [number, number];
  onUpdate: (value: number) => void;
}

export function YearSlider ({ current, range, onUpdate }: YearSliderProps): JSX.Element {
  return (
    <header>
      <h2>Life expectancy by Country, <em>{current}</em></h2>
      <input type="range" value={current} min={range[0]} max={range[1]} onChange={e => onUpdate(Number(e.target.value))}/>
    </header>
  )
}

type GradientLegendProps = {
  colors: ScaleSequential<string>;
  range: [number, number];
  title: string;
}

export function GradientLegend ({ colors, range, title }: GradientLegendProps): JSX.Element {
  const y = Array(range[1] - range[0]).fill(1)
  const color = useCallback((_: number, i: number): string => colors(i + range[0]), [])
  return (
    <VisXYContainer data={[{}]} height={70} width={500}>
      <VisStackedBar orientation={Orientation.Horizontal} x={0} y={y} color={color}/>
      <VisAxis
        type="x"
        label={title}
        position="top"
        numTicks={(range[1] - range[0]) / 5}
        tickFormat={useCallback((i: number) => `${range[0] + i}`, [])}
      />
    </VisXYContainer>
  )
}

export default function TopojsonMap (): JSX.Element {
  const mapData = useMemo(() => ({ areas: data }), [])

  // current year being viewed
  const [year, setYear] = useState(2019)

  // scale functions
  const colorScale = Scale.scaleSequential(palette).domain(ageRange)
  const yearScale = Scale.scaleLinear()
    .domain(yearRange)
    .rangeRound([0, yearRange[1] - yearRange[0]])

  // accessor functions
  const getExpectancy = useCallback((d: AreaDatum) => d.age[yearScale(year)], [year])
  const getAreaColor = useCallback((d: AreaDatum) => colorScale(getExpectancy(d)), [getExpectancy])

  const tooltipTriggers = {
    [TopoJSONMap.selectors.feature]: d =>
      `${d.properties.name}: ${d.data ? getExpectancy(d.data) : 'no data'}`
    ,
  }

  return (
    <div className="topojson-map">
      <YearSlider current={year} range={yearRange} onUpdate={setYear}/>
      <VisSingleContainer data={mapData} height={550} duration={0}>
        <VisTopoJSONMap topojson={WorldMapTopoJSON} areaColor={getAreaColor} disableZoom/>
        <VisTooltip triggers={tooltipTriggers}/>
      </VisSingleContainer>
      <GradientLegend title="Life expectancy (years)" colors={colorScale} range={ageRange}/>
    </div>
  )
}

// packages/shared/examples/topojson-map/topojson-map-solid.tsx
import { Orientation, Scale, TopoJSONMap } from '@unovis/ts'
import { WorldMapTopoJSON } from '@unovis/ts/maps'
import { createSignal, JSX } from 'solid-js'
import { VisAxis, VisSingleContainer, VisStackedBar, VisTooltip, VisTopoJSONMap, VisXYContainer } from '@unovis/solid'

import './styles.css'

import { palette, data, ageRange, yearRange, AreaDatum } from './data'

const TopojsonMap = (): JSX.Element => {
  const mapData = { areas: data }
  const range = yearRange[1] - yearRange[0]

  // scale functions
  const yearScale = Scale.scaleLinear()
    .domain(yearRange)
    .rangeRound([0, range])

  const colorScale = Scale.scaleSequential(palette).domain(ageRange)

  const [year, setYear] = createSignal(2019)

  // accessor functions
  const color = (_: AreaDatum, i: number) => colorScale(i)
  const getExpectancy = (d: AreaDatum) => d.age[yearScale(year())]
  const getAreaColor = (y: number) => (d: AreaDatum) =>
    colorScale(d.age[yearScale(y)])

  const tooltipTriggers = {
    [TopoJSONMap.selectors.feature]: (d) =>
      `${d.properties.name}: ${d.data ? getExpectancy(d.data) : 'no data'}`,
  }

  const gradientSteps = Array(range).fill(1)

  return (
    <div class="topojson-map">
      {/* Year slider */}
      <header>
        <h2>
          Life expectancy by Country, <em>{year()}</em>
        </h2>
        <input
          type="range"
          value={year()}
          min={yearRange[0]}
          max={yearRange[1]}
          onInput={(e) => setYear(e.currentTarget.valueAsNumber)}
        />
      </header>
      {/* Topojson map */}
      <VisSingleContainer data={mapData} height="50dvh" duration={0}>
        <VisTopoJSONMap
          topojson={WorldMapTopoJSON}
          areaColor={getAreaColor(year())}
          disableZoom
        />
        <VisTooltip triggers={tooltipTriggers} />
      </VisSingleContainer>
      {/* Gradient legend */}
      <VisXYContainer data={[{}]} height={70} width={500}>
        <VisStackedBar
          x={0}
          y={gradientSteps}
          color={color}
          orientation={Orientation.Horizontal}
        />
        <VisAxis
          type="x"
          position="top"
          numTicks={range / 5}
          label="Life Expectancy (years)"
        />
      </VisXYContainer>
    </div>
  )
}

export default TopojsonMap
