// packages/vis-svelte/src/html-components/leaflet-flow-map/leaflet-flow-map.svelte
<script lang="ts">
  // !!! This code was automatically generated. You should not change it !!!
  import { LeafletFlowMap, LeafletFlowMapConfigInterface, MapLibreStyleSpecs } from '@unovis/ts'
  import { onMount } from 'svelte'
  import { getActions } from '../../utils/actions'

  // type defs
  type PointDatum = $$Generic
  type FlowDatum = $$Generic

  let config: LeafletFlowMapConfigInterface<PointDatum, FlowDatum>
  $: config = { style, ...$$restProps }

  // component declaration
  let component: LeafletFlowMap<PointDatum, FlowDatum>
  let ref: HTMLDivElement
  const { setConfig, setData } = getActions.apply({
    setConfig: (c: LeafletFlowMapConfigInterface<PointDatum, FlowDatum>) => component?.setConfig(c),
    setData: (d: { points: PointDatum[]; flows?: FlowDatum[] }) => component?.setData(d),
    render: () => component?.render()
  })
  // data and required props
  export let data: { points: PointDatum[]; flows?: FlowDatum[] }
  export let style: MapLibreStyleSpecs | string
  onMount(() => {
    component = new LeafletFlowMap<PointDatum, FlowDatum>(ref, config, data)
    return () => component.destroy()
  })

  // component accessor
  export function getComponent (): LeafletFlowMap<PointDatum, FlowDatum> { return component }

</script>

<vis-leaflet-flow-map bind:this={ref} use:setData={data} use:setConfig={config} />

<style>
  vis-leaflet-flow-map {
    display:block;
    position:relative;
  }
</style>

// packages/vue/src/html-components/leaflet-flow-map/index.vue
<script setup lang="ts" generic="PointDatum extends GenericDataRecord,FlowDatum extends GenericDataRecord">
// !!! This code was automatically generated. You should not change it !!!
import { LeafletFlowMap, LeafletFlowMapConfigInterface, GenericDataRecord, MapLibreStyleSpecs } from '@unovis/ts'
import { onMounted, onUnmounted, computed, ref, watch, nextTick } from 'vue'
import { arePropsEqual, useForwardProps } from '../../utils/props'


// data and required props 
interface Props extends  LeafletFlowMapConfigInterface<PointDatum, FlowDatum> { }
const props = defineProps<Props & { data?: { points: PointDatum[]; flows?: FlowDatum[] } }>()

const data = computed(() => props.data)
// config
const config = useForwardProps(props)

// component declaration
const component = ref<LeafletFlowMap<PointDatum, FlowDatum>>()
const elRef = ref<HTMLDivElement>()

onMounted(() => {
  nextTick(() => {
    if(elRef.value)
    component.value = new LeafletFlowMap<PointDatum, FlowDatum>(elRef.value, config.value, data.value)
    
    
  })
})

onUnmounted(() => {
  component.value?.destroy()
  
})

watch(config, (curr, prev) => {
  if (!arePropsEqual(curr, prev)) {
    component.value?.setConfig(config.value)
  }
})


defineExpose({
  component
})
</script>

<template>
  <div data-vis-leaflet-flow-map ref="elRef"/>
</template>


<style>
  [data-vis-leaflet-flow-map] {
    display:block;
    position:relative;
  }
</style>
