// packages/solid/src/html-components/leaflet-flow-map/index.tsx
// !!! This code was automatically generated. You should not change it !!!
import { LeafletFlowMap } from "@unovis/ts/components/leaflet-flow-map";
import type { LeafletFlowMapConfigInterface } from "@unovis/ts/components/leaflet-flow-map/config";
import type { GenericDataRecord } from "@unovis/ts/types/data";
import { createSignal, onCleanup, createEffect, on, onMount } from 'solid-js'
import { arePropsEqual } from '../../utils/props'

export type VisLeafletFlowMapProps<PointDatum extends GenericDataRecord, FlowDatum extends GenericDataRecord> = LeafletFlowMapConfigInterface<PointDatum, FlowDatum>& {
  data?: { points: PointDatum[]; flows?: FlowDatum[] };
};

export const VisLeafletFlowMapSelectors = LeafletFlowMap.selectors

export function VisLeafletFlowMap<PointDatum extends GenericDataRecord, FlowDatum extends GenericDataRecord>(props: VisLeafletFlowMapProps<PointDatum, FlowDatum>) {
  const [component, setComponent] = createSignal<LeafletFlowMap<PointDatum, FlowDatum>>()
   
  const [ref, setRef] = createSignal<HTMLDivElement>()

  onMount(() => {
    const r = ref()
    if(r) setComponent(new LeafletFlowMap<PointDatum, FlowDatum>(r, props, props.data));
    
    
  })

  onCleanup(() => {
    component()?.destroy()
    
  })

  createEffect(
    on(
      () => ({ ...props }),
      (curr, prev) => {
        if (!arePropsEqual(prev, curr)) {
          component()?.setConfig(curr)
          
        }
      },
      {
        defer: true
      }
    )
  )

  

  return <div  ref={setRef} style={{ display:"block", position:"relative" }} />
}

// packages/vue/src/html-components/leaflet-flow-map/index.vue
<script setup lang="ts" generic="PointDatum extends GenericDataRecord,FlowDatum extends GenericDataRecord">
// !!! This code was automatically generated. You should not change it !!!
import { LeafletFlowMap, LeafletFlowMapConfigInterface, GenericDataRecord, MapLibreStyleSpecs } from '@unovis/ts'
import { onMounted, onUnmounted, computed, ref, watch, nextTick } from 'vue'
import { arePropsEqual, useForwardProps } from '../../utils/props'


// data and required props 
type Props = LeafletFlowMapConfigInterface<PointDatum, FlowDatum>
const props = defineProps<Props & { data?: { points: PointDatum[]; flows?: FlowDatum[] } }>()

const data = computed(() => props.data)
// config
const config = useForwardProps(props)

// component declaration
const component = ref<LeafletFlowMap<PointDatum, FlowDatum>>()
const elRef = ref<HTMLDivElement>()

onMounted(() => {
  nextTick(() => {
    if(elRef.value)
    component.value = new LeafletFlowMap<PointDatum, FlowDatum>(elRef.value, config.value, data.value)
    
    
  })
})

onUnmounted(() => {
  component.value?.destroy()
  
})

watch(config, (curr, prev) => {
  if (!arePropsEqual(curr, prev)) {
    component.value?.setConfig(config.value)
  }
})


defineExpose({
  component
})
</script>

<script lang="ts">
export const VisLeafletFlowMapSelectors = LeafletFlowMap.selectors
</script>

<template>
  <div data-vis-leaflet-flow-map ref="elRef"/>
</template>


<style>
  [data-vis-leaflet-flow-map] {
    display:block;
    position:relative;
  }
</style>
