// packages/shared/examples/elk-layered-graph/elk-layered-graph-solid.tsx
import { JSX } from 'solid-js'
import { GraphLayoutType, GraphNodeShape } from '@unovis/ts'
import { VisGraph, VisSingleContainer } from '@unovis/solid'

import './styles.css'

import { data, NodeDatum, panels } from './data'

const ElkLayerdGraph = (): JSX.Element => {
  const layoutElkSettings = {
    'layered.crossingMinimization.forceNodeModelOrder': 'true',
    'elk.direction': 'RIGHT',
    'elk.padding': '[top=30.0,left=10.0,bottom=30.0,right=10.0]',
    'nodePlacement.strategy': 'SIMPLE',
  }

  const nodeShape = GraphNodeShape.Square
  const nodeStrokeWidth = 1.5
  const nodeLabel = (n: NodeDatum) => n.id
  const layoutType = GraphLayoutType.Elk
  const layoutElkNodeGroups = [
    (d: NodeDatum) => d.group ?? null,
    (d: NodeDatum) => d.subGroup ?? null,
  ]

  return (
    <div class="chart">
      <VisSingleContainer data={data} height="50dvh">
        <VisGraph
          nodeShape={nodeShape}
          nodeStrokeWidth={nodeStrokeWidth}
          nodeLabel={nodeLabel}
          layoutType={layoutType}
          layoutElkNodeGroups={layoutElkNodeGroups}
          layoutElkSettings={layoutElkSettings}
          panels={panels}
          disableZoom
        />
      </VisSingleContainer>
    </div>
  )
}

export default ElkLayerdGraph

// packages/website/src/examples/elk-layered-graph/elk-layered-graph.tsx
/* eslint-disable @typescript-eslint/naming-convention */
import React, { useCallback, useMemo } from 'react'
import { VisSingleContainer, VisGraph } from '@unovis/react'
import { GraphLayoutType, GraphNodeShape } from '@unovis/ts'

import { data, NodeDatum, LinkDatum, panels } from './data'

import './styles.css'

export default function ForceLayoutGraph (): JSX.Element {
  const layoutElkSettings = {
    'layered.crossingMinimization.forceNodeModelOrder': 'true',
    'elk.direction': 'RIGHT',
    'elk.padding': '[top=30.0,left=0.0,bottom=30.0,right=0.0]',
    'spacing.nodeNodeBetweenLayers': '250',
  }

  return (
    <div className='chart'>
      <VisSingleContainer data={data} height={'60vh'}>
        <VisGraph<NodeDatum, LinkDatum>
          nodeShape={GraphNodeShape.Square}
          nodeStrokeWidth={1.5}
          nodeLabel={useCallback((n: NodeDatum) => n.id, [])}
          layoutType={GraphLayoutType.Elk}
          layoutElkNodeGroups={useMemo(() => [
            (d: NodeDatum): string | null => d.group ?? null,
            (d: NodeDatum): string | null => d.subGroup ?? null,
          ], [])}
          layoutElkSettings={layoutElkSettings}
          panels={panels}
          disableZoom
        />
      </VisSingleContainer>
    </div>
  )
}
