// packages/svelte/src/components/free-brush/free-brush.svelte
<script lang="ts">
  // !!! This code was automatically generated. You should not change it !!!
  import { FreeBrush, FreeBrushConfigInterface } from '@unovis/ts'
  import { getContext, onMount } from 'svelte'
  import { arePropsEqual } from '../../utils/props'

  // type defs
  type Datum = $$Generic

  // data and required props
  // eslint-disable-next-line no-undef-init
  export let data: Datum[] = undefined

  // config
  let prevConfig: FreeBrushConfigInterface<Datum>
  let config: FreeBrushConfigInterface<Datum>
  $: config = { ...$$restProps }

  // component declaration
  let component: FreeBrush<Datum>
  const { setComponent, removeComponent } = getContext('container')

  onMount(() => {
    component = new FreeBrush<Datum>(config)
    setComponent(component)
    return () => { removeComponent(component) as void }
  })

  $: component?.setData(data)
  $: if (!arePropsEqual(prevConfig, config)) {
    component?.setConfig(config)
    prevConfig = config
  }

  // component accessor
  export function getComponent (): FreeBrush<Datum> { return component }

</script>

<vis-component/>

// packages/vis-react/src/components/free-brush/index.tsx
/* eslint-disable notice/notice */
// !!! This code was automatically generated. You should not change it !!!
import { useEffect, useRef, useState } from 'react'
// import { FreeBrush, FreeBrushConfigInterface } from '@volterra/vis'
import { FreeBrush, FreeBrushConfigInterface, GenericDataRecord } from '@volterra/vis'

export type VisFreeBrushProps<Datum = GenericDataRecord> = FreeBrushConfigInterface<Datum> & { data?: Datum[] }

// eslint-disable-next-line @typescript-eslint/naming-convention
export function VisFreeBrush<Datum = GenericDataRecord> (props: VisFreeBrushProps<Datum>): JSX.Element {
  // eslint-disable-next-line @typescript-eslint/naming-convention
  type RefType = HTMLDivElement & { __component__: FreeBrush<Datum> }
  const ref = useRef<RefType>(null)
  const [component] = useState<FreeBrush<Datum>>(new FreeBrush(props))

  // On Mount
  useEffect(() => {
    (ref.current as RefType).__component__ = component
  }, [])

  // On Props Update
  useEffect(() => {
    component?.setData(props.data ?? [])
    component?.setConfig(props)
  })

  return <vis-component ref={ref} />
}
