// packages/vis-react/src/components/brush/index.tsx
/* eslint-disable notice/notice */
// !!! This code was automatically generated. You should not change it !!!
import React, { useEffect, useRef, useState } from 'react'
import { Brush, BrushConfigInterface } from '@volterra/vis'

// Utils
import { arePropsEqual } from 'src/utils/react'

// Types
import { WithSelectors } from 'src/types/react'
import { VisComponentElement } from 'src/types/dom'

export type VisBrushProps<Datum> = BrushConfigInterface<Datum> & { data?: Datum[] }

// eslint-disable-next-line @typescript-eslint/naming-convention
function VisBrushFC<Datum> (props: VisBrushProps<Datum>): JSX.Element {
  const ref = useRef<VisComponentElement<Brush<Datum>>>(null)
  const [component] = useState<Brush<Datum>>(new Brush(props))

  // On Mount
  useEffect(() => {
    (ref.current as VisComponentElement<Brush<Datum>>).__component__ = component
  }, [])

  // On Props Update
  useEffect(() => {
    component?.setData(props.data ?? [])
    component?.setConfig(props)
  })

  return <vis-component ref={ref} />
}
const memoizedComponent = React.memo(VisBrushFC, arePropsEqual)
export const VisBrush = memoizedComponent as WithSelectors<typeof memoizedComponent, typeof Brush.selectors>
VisBrush.selectors = Brush.selectors

// packages/svelte/src/components/brush/brush.svelte
<script lang="ts">
  // !!! This code was automatically generated. You should not change it !!!
  import { Brush, BrushConfigInterface } from '@unovis/ts'
  import { onMount, getContext } from 'svelte'
  
  import type { Lifecycle } from '../../types/context'
  import { arePropsEqual } from '../../utils/props'
  // type defs
  type Datum = $$Generic
  
  // data and required props
  // eslint-disable-next-line no-undef-init
export let data: Datum[] = undefined

  // config
  let prevConfig: BrushConfigInterface<Datum>
  let config: BrushConfigInterface<Datum>
  $: config = { ...$$restProps }

  // component declaration
  let component: Brush<Datum>
  const lifecycle = getContext<Lifecycle>('component')

  onMount(() => {
    component = new Brush<Datum>(config)
    return () => component?.destroy()
    })
  $: component?.setData(data)
  $: if(!arePropsEqual(prevConfig, config)) {
    component?.setConfig(config)
    prevConfig = config
  }

  // component accessor
  export function getComponent (): Brush<Datum> { return component }

</script>

<vis-component use:lifecycle={component}/>
