// packages/shared/examples/hierarchical-chord-diagram/hierarchical-chord-diagram-solid.tsx
import { JSX } from 'solid-js'
import { ChordLabelAlignment } from '@unovis/ts'
import { VisChordDiagram, VisSingleContainer } from '@unovis/solid'

import { nodes, links, colorMap, NodeDatum, LinkDatum } from './data'

const HierarchicalChordDiagram = (): JSX.Element => {
  const data = { links, nodes }
  const linkColor = (l: LinkDatum) => colorMap.get(l.source.country)
  const nodeColor = (n: NodeDatum) => colorMap.get(n.country ?? n.key)
  const nodeLabel = (n: NodeDatum) => n.id ?? n.key
  const nodeLabelColor = (n: NodeDatum) =>
    n.height && 'var(--vis-tooltip-text-color)'

  return (
    <VisSingleContainer data={data} height='50dvh'>
      <VisChordDiagram
        nodeLevels={['country']}
        linkColor={linkColor}
        nodeColor={nodeColor}
        nodeLabel={nodeLabel}
        nodeLabelColor={nodeLabelColor}
        nodeLabelAlignment={ChordLabelAlignment.Perpendicular}
      />
    </VisSingleContainer>
  )
}

export default HierarchicalChordDiagram

// packages/shared/examples/hierarchical-chord-diagram/hierarchical-chord-diagram.tsx
import React, { useCallback } from 'react'
import { VisSingleContainer, VisChordDiagram } from '@unovis/react'
import { ChordLabelAlignment } from '@unovis/ts'

import { nodes, links, colorMap, NodeDatum, LinkDatum } from './data'

export default function HierarchicalChordDiagram (): JSX.Element {
  return (
    <VisSingleContainer data={{ links, nodes }} height={'60vh'}>
      <VisChordDiagram<NodeDatum, LinkDatum>
        nodeLevels={['country']}
        linkColor={useCallback(l => colorMap.get(l.source.country), [])}
        nodeColor={useCallback(n => colorMap.get(n.country ?? n.key), [])}
        nodeLabel={useCallback(n => n.id ?? n.key, [])}
        nodeLabelColor={useCallback(n => n.height && 'var(--vis-tooltip-text-color)', [])}
        nodeLabelAlignment={ChordLabelAlignment.Perpendicular}
      />
    </VisSingleContainer>
  )
}
