// packages/shared/examples/basic-circular-bar-chart/basic-circular-bar-chart-solid.tsx
import { JSX } from 'solid-js'
import { VisBulletLegend, VisCircularBar, VisCircularBarSelectors, VisSingleContainer, VisTooltip } from '@unovis/solid'
import type { CircularBarArcDatum } from '@unovis/ts'

import { data, DataRecord, maxValue } from './data'
import './styles.css'

const BasicCircularBarChart = (): JSX.Element => {
  const legendItems = data.map(d => ({ name: d.key, color: d.color }))

  return (
    <div class='circular-bar-chart'>
      <VisBulletLegend items={legendItems} />
      <VisSingleContainer height='50dvh'>
        <VisCircularBar
          value={(d: DataRecord) => d.value}
          color={(d: DataRecord) => d.color}
          icon={(d: DataRecord) => d.icon}
          maxValue={maxValue}
          data={data}
        />
        <VisTooltip triggers={{
          [VisCircularBarSelectors.bar]: (d: CircularBarArcDatum<DataRecord>) => {
            const max = maxValue[d.index] ?? '—'
            return `<strong>${d.data.key}</strong><br/>${d.value} / ${max} ${d.data.unit}`
          },
        }}
        />
      </VisSingleContainer>
    </div>
  )
}

export default BasicCircularBarChart

// packages/shared/examples/basic-circular-bar-chart/basic-circular-bar-chart.tsx
import React, { useCallback } from 'react'
import { VisSingleContainer, VisCircularBar, VisCircularBarSelectors, VisTooltip, VisBulletLegend } from '@unovis/react'
import type { CircularBarArcDatum } from '@unovis/ts'

import { data, DataRecord, maxValue } from './data'
import './styles.css'

const legendItems = data.map(d => ({ name: d.key, color: d.color }))

export default function BasicCircularBarChart (): React.ReactElement {
  return (
    <div className='circular-bar-chart'>
      <VisBulletLegend items={legendItems}/>
      <VisSingleContainer height={400}>
        <VisCircularBar<DataRecord>
          value={useCallback(d => d.value, [])}
          color={useCallback(d => d.color, [])}
          icon={useCallback(d => d.icon, [])}
          maxValue={maxValue}
          data={data}
        />
        <VisTooltip triggers={{
          [VisCircularBarSelectors.bar]: (d: CircularBarArcDatum<DataRecord>) => {
            const max = maxValue[d.index] ?? '—'
            return `<strong>${d.data.key}</strong><br/>${d.value} / ${max} ${d.data.unit}`
          },
        }}
        />
      </VisSingleContainer>
    </div>
  )
}
