// packages/vue/src/components/stacked-bar/index.vue
<script setup lang="ts" generic="Datum">
// !!! This code was automatically generated. You should not change it !!!

import type { StackedBarConfigInterface } from '@unovis/ts/components/stacked-bar/config'
import { StackedBar } from '@unovis/ts/components/stacked-bar'
import { computed, inject, nextTick, onMounted, onUnmounted, ref, watch } from 'vue'
import { componentAccessorKey } from '../../utils/context'
import { arePropsEqual, useForwardProps } from '../../utils/props'

const props = defineProps<Props & { data?: Datum[] }>()

const accessor = inject(componentAccessorKey)

// data and required props
type Props = StackedBarConfigInterface<Datum>
const data = computed(() => accessor.data.value ?? props.data)
// config
const config = useForwardProps(props)

// component declaration
const component = ref<StackedBar<Datum>>()

onMounted(() => {
  nextTick(() => {
    component.value = new StackedBar<Datum>(config.value)
    component.value?.setData(data.value)
    accessor.update(component.value)
  })
})

onUnmounted(() => {
  component.value?.destroy()
  accessor.destroy()
})

watch(config, (curr, prev) => {
  if (!arePropsEqual(curr, prev)) {
    component.value?.setConfig(config.value)
    component.value?.render()
  }
})

watch(data, () => {
  component.value?.setData(data.value)
})

defineExpose({
  component,
})
</script>

<script lang="ts">
export const VisStackedBarSelectors = StackedBar.selectors
</script>

<template>
  <div data-vis-component />
</template>

// packages/svelte/src/components/stacked-bar/stacked-bar.svelte
<script lang="ts">
  // !!! This code was automatically generated. You should not change it !!!
  import { StackedBar } from '@unovis/ts/components/stacked-bar'
  import type { StackedBarConfigInterface } from '@unovis/ts/components/stacked-bar/config'
  import type { NumericAccessor } from '@unovis/ts/types/accessor'
  import { onMount, getContext } from 'svelte'

  import type { Lifecycle } from '../../types/context'
  import { arePropsEqual } from '../../utils/props'
  // type defs
  type Datum = $$Generic

  // data and required props
  // eslint-disable-next-line no-undef-init
  export let data: Datum[] = undefined
  export let x: NumericAccessor<Datum>
  export let y: NumericAccessor<Datum> | NumericAccessor<Datum>[]

  // config
  let prevConfig: StackedBarConfigInterface<Datum>
  let config: StackedBarConfigInterface<Datum>
  $: config = { x, y, ...$$restProps }

  // component declaration
  let component: StackedBar<Datum>
  const lifecycle = getContext<Lifecycle>('component')

  onMount(() => {
    component = new StackedBar<Datum>(config)
    return () => component?.destroy()
  })
  $: component?.setData(data)
  $: if (!arePropsEqual(prevConfig, config)) {
    component?.setConfig(config)
    prevConfig = config
  }

  // component accessor
  export function getComponent (): StackedBar<Datum> { return component }

</script>

<vis-component use:lifecycle={component}/>
