// packages/vis-react/src/components/stacked-bar/index.tsx
/* eslint-disable notice/notice */
// !!! This code was automatically generated. You should not change it !!!
import { useEffect, useRef, useState } from 'react'
// import { StackedBar, StackedBarConfigInterface } from '@volterra/vis'
import { StackedBar, StackedBarConfigInterface } from '@volterra/vis'

// Types
import { VisComponentElement } from 'src/types/dom'

export type VisStackedBarProps<Datum> = StackedBarConfigInterface<Datum> & { data?: Datum[] }

// eslint-disable-next-line @typescript-eslint/naming-convention
export function VisStackedBar<Datum> (props: VisStackedBarProps<Datum>): JSX.Element {
  const ref = useRef<VisComponentElement<StackedBar<Datum>>>(null)
  const [component] = useState<StackedBar<Datum>>(new StackedBar(props))

  // On Mount
  useEffect(() => {
    (ref.current as VisComponentElement<StackedBar<Datum>>).__component__ = component
  }, [])

  // On Props Update
  useEffect(() => {
    component?.setData(props.data ?? [])
    component?.setConfig(props)
  })

  return <vis-component ref={ref} />
}

// packages/svelte/src/components/stacked-bar/stacked-bar.svelte
<script lang="ts">
  // !!! This code was automatically generated. You should not change it !!!
  import { StackedBar, StackedBarConfigInterface, NumericAccessor } from '@unovis/ts'
  import { onMount, getContext } from 'svelte'
  
  import type { Lifecycle } from '../../types/context'
  import { arePropsEqual } from '../../utils/props'
  // type defs
  type Datum = $$Generic
  
  // data and required props
  // eslint-disable-next-line no-undef-init
export let data: Datum[] = undefined
  export let x: NumericAccessor<Datum>
  export let y: NumericAccessor<Datum> | NumericAccessor<Datum>[]

  // config
  let prevConfig: StackedBarConfigInterface<Datum>
  let config: StackedBarConfigInterface<Datum>
  $: config = { x,  y, ...$$restProps }

  // component declaration
  let component: StackedBar<Datum>
  const lifecycle = getContext<Lifecycle>('component')

  onMount(() => {
    component = new StackedBar<Datum>(config)
    return () => component?.destroy()
    })
  $: component?.setData(data)
  $: if(!arePropsEqual(prevConfig, config)) {
    component?.setConfig(config)
    prevConfig = config
  }

  // component accessor
  export function getComponent (): StackedBar<Datum> { return component }

</script>

<vis-component use:lifecycle={component}/>
