// packages/vue/src/components/chord-diagram/index.vue
<script setup lang="ts" generic="N extends ChordInputNode, L extends ChordInputLink">
// !!! This code was automatically generated. You should not change it !!!

import type { ChordDiagramConfigInterface } from '@unovis/ts/components/chord-diagram/config'
import type { ChordInputLink, ChordInputNode } from '@unovis/ts/components/chord-diagram/types'
import { ChordDiagram } from '@unovis/ts/components/chord-diagram'
import { computed, inject, nextTick, onMounted, onUnmounted, ref, watch } from 'vue'
import { componentAccessorKey } from '../../utils/context'
import { arePropsEqual, useForwardProps } from '../../utils/props'

const props = defineProps<Props & { data?: { nodes: N[], links?: L[] } }>()

const accessor = inject(componentAccessorKey)

// data and required props
type Props = ChordDiagramConfigInterface<N, L>
const data = computed(() => accessor.data.value ?? props.data)
// config
const config = useForwardProps(props)

// component declaration
const component = ref<ChordDiagram<N, L>>()

onMounted(() => {
  nextTick(() => {
    component.value = new ChordDiagram<N, L>(config.value)
    component.value?.setData(data.value)
    accessor.update(component.value)
  })
})

onUnmounted(() => {
  component.value?.destroy()
  accessor.destroy()
})

watch(config, (curr, prev) => {
  if (!arePropsEqual(curr, prev)) {
    component.value?.setConfig(config.value)
    component.value?.render()
  }
})

watch(data, () => {
  component.value?.setData(data.value)
})

defineExpose({
  component,
})
</script>

<script lang="ts">
export const VisChordDiagramSelectors = ChordDiagram.selectors
</script>

<template>
  <div data-vis-component />
</template>

// packages/solid/src/components/chord-diagram/index.tsx
// !!! This code was automatically generated. You should not change it !!!
import { ChordDiagram } from "@unovis/ts/components/chord-diagram";
import type { ChordDiagramConfigInterface } from "@unovis/ts/components/chord-diagram/config";
import type { ChordInputNode, ChordInputLink } from "@unovis/ts/components/chord-diagram/types";
import { createSignal, onCleanup, createEffect, on, onMount } from 'solid-js'
import { arePropsEqual } from '../../utils/props'
import { useVisContainer } from "../../utils/context";

export type VisChordDiagramProps<N extends ChordInputNode, L extends ChordInputLink> = ChordDiagramConfigInterface<N, L>& {
  data?: { nodes: N[]; links?: L[] };
};

export const VisChordDiagramSelectors = ChordDiagram.selectors

export function VisChordDiagram<N extends ChordInputNode, L extends ChordInputLink>(props: VisChordDiagramProps<N, L>) {
  const [component, setComponent] = createSignal<ChordDiagram<N, L>>()
   const ctx = useVisContainer();
  
  onMount(() => {
    setComponent(new ChordDiagram<N, L>(props));
    if (props.data) component()?.setData(props.data)
    ctx.update("component", component);
  })

  onCleanup(() => {
    component()?.destroy()
    ctx.destroy("component");
  })

  createEffect(
    on(
      () => ({ ...props }),
      (curr, prev) => {
        if (!arePropsEqual(prev, curr)) {
          component()?.setConfig(curr)
          ctx.dirty()
        }
      },
      {
        defer: true
      }
    )
  )

  
  createEffect(
    on(
      () => props.data,
      (data) => {
        if (data) {
          component()?.setData(data)
          ctx.dirty()
        }
      },
      {
        defer: true
      }
    )
  );


  return <div data-vis-component  />
}
