// packages/solid/src/components/annotations/index.tsx
// !!! This code was automatically generated. You should not change it !!!
import { Annotations } from "@unovis/ts/components/annotations";
import type { AnnotationsConfigInterface } from "@unovis/ts/components/annotations/config";
import { createSignal, onCleanup, createEffect, on, onMount } from 'solid-js'
import { arePropsEqual } from '../../utils/props'
import { useVisContainer } from "../../utils/context";

export type VisAnnotationsProps = AnnotationsConfigInterface

export const VisAnnotationsSelectors = Annotations.selectors

export function VisAnnotations(props: VisAnnotationsProps) {
  const [component, setComponent] = createSignal<Annotations>()
   const ctx = useVisContainer();
  
  onMount(() => {
    setComponent(new Annotations(props));
    
    ctx.update("annotations", component);
  })

  onCleanup(() => {
    component()?.destroy()
    ctx.destroy("annotations");
  })

  createEffect(
    on(
      () => ({ ...props }),
      (curr, prev) => {
        if (!arePropsEqual(prev, curr)) {
          component()?.setConfig(curr)
          ctx.dirty()
        }
      },
      {
        defer: true
      }
    )
  )

  

  return <div data-vis-annotations  />
}

// packages/vue/src/components/annotations/index.vue
<script setup lang="ts">
// !!! This code was automatically generated. You should not change it !!!

import type { AnnotationsConfigInterface } from '@unovis/ts/components/annotations/config'
import { Annotations } from '@unovis/ts/components/annotations'
import { inject, nextTick, onMounted, onUnmounted, ref, watch } from 'vue'
import { annotationsAccessorKey } from '../../utils/context'
import { arePropsEqual, useForwardProps } from '../../utils/props'

const props = defineProps<Props & { data?: null }>()

const accessor = inject(annotationsAccessorKey)

// data and required props
type Props = AnnotationsConfigInterface
// config
const config = useForwardProps(props)

// component declaration
const component = ref<Annotations>()

onMounted(() => {
  nextTick(() => {
    component.value = new Annotations(config.value)

    accessor.update(component.value)
  })
})

onUnmounted(() => {
  component.value?.destroy()
  accessor.destroy()
})

watch(config, (curr, prev) => {
  if (!arePropsEqual(curr, prev)) {
    component.value?.setConfig(config.value)
    component.value?.render()
  }
})

defineExpose({
  component,
})
</script>

<script lang="ts">
export const VisAnnotationsSelectors = Annotations.selectors
</script>

<template>
  <div data-vis-annotations />
</template>
