// packages/svelte/src/components/annotations/annotations.svelte
<script lang="ts">
  // !!! This code was automatically generated. You should not change it !!!
  import { Annotations, AnnotationsConfigInterface, AnnotationItem } from '@unovis/ts'
  import { onMount, getContext } from 'svelte'

  import type { Lifecycle } from '../../types/context'
  import { arePropsEqual } from '../../utils/props'


  // data and required props
  // eslint-disable-next-line no-undef-init
  export let data: Datum[] = undefined
  export let items: AnnotationItem[] | undefined

  // config
  let prevConfig: AnnotationsConfigInterface
  let config: AnnotationsConfigInterface
  $: config = { items, ...$$restProps }

  // component declaration
  let component: Annotations
  const lifecycle = getContext<Lifecycle>('annotations')

  onMount(() => {
    component = new Annotations(config)
    return () => component?.destroy()
  })
  $: component?.setData(data)
  $: if (!arePropsEqual(prevConfig, config)) {
    component?.setConfig(config)
    prevConfig = config
  }

  // component accessor
  export function getComponent (): Annotations { return component }

</script>

<vis-annotations use:lifecycle={component}/>

// packages/vue/src/components/annotations/index.vue
<script setup lang="ts" >
// !!! This code was automatically generated. You should not change it !!!
import { Annotations, AnnotationsConfigInterface, AnnotationItem } from '@unovis/ts'
import { onMounted, onUnmounted, computed, ref, watch, nextTick, inject } from 'vue'
import { arePropsEqual, useForwardProps } from '../../utils/props'
import { annotationsAccessorKey } from '../../utils/context'

const accessor = inject(annotationsAccessorKey)

// data and required props 
interface Props extends  AnnotationsConfigInterface { }
const props = defineProps<Props & { data?: Datum[] }>()

const data = computed(() => accessor.data.value ?? props.data)
// config
const config = useForwardProps(props)

// component declaration
const component = ref<Annotations>()


onMounted(() => {
  nextTick(() => {
    component.value = new Annotations(config.value)
    component.value?.setData(data.value)
    accessor.update(component.value)
  })
})

onUnmounted(() => {
  component.value?.destroy()
  accessor.destroy()
})

watch(config, (curr, prev) => {
  if (!arePropsEqual(curr, prev)) {
    component.value?.setConfig(config.value)
  }
})

watch(data, () => {
  component.value?.setData(data.value)
})

defineExpose({
  component
})
</script>

<template>
  <div data-vis-annotations />
</template>
