// packages/vue/src/html-components/leaflet-flow-map/index.vue
<script setup lang="ts" generic="PointDatum extends GenericDataRecord,FlowDatum extends GenericDataRecord">
// !!! This code was automatically generated. You should not change it !!!
import { LeafletFlowMap, LeafletFlowMapConfigInterface, GenericDataRecord, MapLibreStyleSpecs } from '@unovis/ts'
import { onMounted, onUnmounted, computed, ref, watch, nextTick } from 'vue'
import { arePropsEqual, useForwardProps } from '../../utils/props'


// data and required props 
interface Props extends  LeafletFlowMapConfigInterface<PointDatum, FlowDatum> { }
const props = defineProps<Props & { data?: { points: PointDatum[]; flows?: FlowDatum[] } }>()

const data = computed(() => props.data)
// config
const config = useForwardProps(props)

// component declaration
const component = ref<LeafletFlowMap<PointDatum, FlowDatum>>()
const elRef = ref<HTMLDivElement>()

onMounted(() => {
  nextTick(() => {
    if(elRef.value)
    component.value = new LeafletFlowMap<PointDatum, FlowDatum>(elRef.value, config.value, data.value)
    
    
  })
})

onUnmounted(() => {
  component.value?.destroy()
  
})

watch(config, (curr, prev) => {
  if (!arePropsEqual(curr, prev)) {
    component.value?.setConfig(config.value)
  }
})


defineExpose({
  component
})
</script>

<template>
  <div data-vis-leaflet-flow-map ref="elRef"/>
</template>


<style>
  [data-vis-leaflet-flow-map] {
    display:block;
    position:relative;
  }
</style>

// packages/svelte/src/html-components/leaflet-flow-map/leaflet-flow-map.svelte
<script lang="ts">
  // !!! This code was automatically generated. You should not change it !!!
  import { LeafletFlowMap, type LeafletFlowMapConfigInterface, type GenericDataRecord, type MapLibreStyleSpecs } from '@unovis/ts'
  import { onMount } from 'svelte'

  import { arePropsEqual } from '../../utils/props'
  // type defs
  type PointDatum = $$Generic<GenericDataRecord>
  type FlowDatum = $$Generic<GenericDataRecord>

  // data and required props
  // eslint-disable-next-line no-undef-init
  export let data: { points: PointDatum[]; flows?: FlowDatum[] } = undefined
  export let style: MapLibreStyleSpecs | string | undefined

  // config
  let prevConfig: LeafletFlowMapConfigInterface<PointDatum, FlowDatum>
  let config: LeafletFlowMapConfigInterface<PointDatum, FlowDatum>
  $: config = { style, ...$$restProps }

  // component declaration
  let component: LeafletFlowMap<PointDatum, FlowDatum>
  let ref: HTMLDivElement

  onMount(() => {
    component = new LeafletFlowMap<PointDatum, FlowDatum>(ref, config, data)
    return () => component?.destroy()
  })
  $: component?.setData(data)
  $: if (!arePropsEqual(prevConfig, config)) {
    component?.setConfig(config)
    prevConfig = config
  }

  // component accessor
  export function getComponent (): LeafletFlowMap<PointDatum, FlowDatum> { return component }

</script>

<vis-leaflet-flow-map bind:this={ref}></vis-leaflet-flow-map>

<style>
  vis-leaflet-flow-map {
    display:block;
    position:relative;
  }
</style>
