// packages/vue/src/components/plotline/index.vue
<script setup lang="ts" generic="Datum">
// !!! This code was automatically generated. You should not change it !!!

import type { PlotlineConfigInterface } from '@unovis/ts/components/plotline/config'
import { Plotline } from '@unovis/ts/components/plotline'
import { inject, nextTick, onMounted, onUnmounted, ref, watch } from 'vue'
import { componentAccessorKey } from '../../utils/context'
import { arePropsEqual, useForwardProps } from '../../utils/props'

const props = defineProps<Props & { data?: null }>()

const accessor = inject(componentAccessorKey)

// data and required props
type Props = PlotlineConfigInterface<Datum>
// config
const config = useForwardProps(props)

// component declaration
const component = ref<Plotline<Datum>>()

onMounted(() => {
  nextTick(() => {
    component.value = new Plotline<Datum>(config.value)

    accessor.update(component.value)
  })
})

onUnmounted(() => {
  component.value?.destroy()
  accessor.destroy()
})

watch(config, (curr, prev) => {
  if (!arePropsEqual(curr, prev)) {
    component.value?.setConfig(config.value)
    component.value?.render()
  }
})

defineExpose({
  component,
})
</script>

<script lang="ts">
export const VisPlotlineSelectors = Plotline.selectors
</script>

<template>
  <div data-vis-component />
</template>

// packages/solid/src/components/plotline/index.tsx
// !!! This code was automatically generated. You should not change it !!!
import { Plotline } from "@unovis/ts/components/plotline";
import type { PlotlineConfigInterface } from "@unovis/ts/components/plotline/config";
import { createSignal, onCleanup, createEffect, on, onMount } from 'solid-js'
import { arePropsEqual } from '../../utils/props'
import { useVisContainer } from "../../utils/context";

export type VisPlotlineProps<Datum> = PlotlineConfigInterface<Datum>

export const VisPlotlineSelectors = Plotline.selectors

export function VisPlotline<Datum>(props: VisPlotlineProps<Datum>) {
  const [component, setComponent] = createSignal<Plotline<Datum>>()
   const ctx = useVisContainer();
  
  onMount(() => {
    setComponent(new Plotline<Datum>(props));
    
    ctx.update("component", component);
  })

  onCleanup(() => {
    component()?.destroy()
    ctx.destroy("component");
  })

  createEffect(
    on(
      () => ({ ...props }),
      (curr, prev) => {
        if (!arePropsEqual(prev, curr)) {
          component()?.setConfig(curr)
          ctx.dirty()
        }
      },
      {
        defer: true
      }
    )
  )

  

  return <div data-vis-component  />
}
