// packages/shared/examples/force-graph/force-graph.tsx
import React, { useCallback, useMemo } from 'react'
import { VisSingleContainer, VisGraph } from '@unovis/react'
import { GraphForceLayoutSettings, GraphLayoutType } from '@unovis/ts'

import { data, NodeDatum, LinkDatum } from './data'

export default function ForceLayoutGraph (): JSX.Element {
  const forceLayoutSettings: GraphForceLayoutSettings = {
    forceXStrength: 0.1,
    forceYStrength: 0.4,
    charge: -700,
  }
  return (
    <VisSingleContainer data={data} height={'60vh'}>
      <VisGraph<NodeDatum, LinkDatum>
        layoutType={GraphLayoutType.Force}
        forceLayoutSettings={useMemo(() => forceLayoutSettings, [])}
        linkLabel={useCallback((l: LinkDatum) => ({ text: l.chapter }), [])}
        nodeFill={useCallback((n: NodeDatum) => n.color, [])}
        nodeLabel={useCallback(n => n.id, [])}
        nodeSize={40}
      />
    </VisSingleContainer>
  )
}

// packages/shared/examples/force-graph/force-graph.svelte
<script lang='ts'>
  import { VisSingleContainer, VisGraph } from '@unovis/svelte'
  import { GraphForceLayoutSettings, GraphLayoutType } from '@unovis/ts'
  import { data, LinkDatum, NodeDatum } from './data'

  const forceLayoutSettings: GraphForceLayoutSettings = {
    forceXStrength: 0.2,
    forceYStrength: 0.4,
    charge: -700,
  }
  const linkLabel = (l: LinkDatum) => ({ text: l.chapter })
  const nodeLabel = (n: NodeDatum) => n.id
  const nodeFill = (n: NodeDatum) => n.color

</script>

<VisSingleContainer {data} height={'60vh'}>
  <VisGraph
    layoutType="{GraphLayoutType.Force}"
    nodeSize={40}
    {forceLayoutSettings}
    {linkLabel}
    {nodeFill}
    {nodeLabel}
  />
</VisSingleContainer>
