// packages/shared/examples/basic-grouped-bar/basic-grouped-bar.tsx
import React, { useCallback } from 'react'
import { VisXYContainer, VisGroupedBar, VisAxis, VisBulletLegend } from '@unovis/react'

import { data, capitalize, colors } from './data'

const legendItems = Object.entries(colors).map(([n, c]) => ({
  name: capitalize(n),
  color: c,
}))

export default function BasicGroupedBar (): JSX.Element {
  return (
    <>
      <h2>U.S. Election Popular Vote Results by Political Party</h2>
      <VisBulletLegend items={legendItems}/>
      <VisXYContainer height={'50vh'} data={data}>
        <VisGroupedBar
          x={useCallback(d => d.year, [])}
          y={[
            useCallback(d => d.republican, []),
            useCallback(d => d.democrat, []),
            useCallback(d => d.other, []),
            useCallback(d => d.libertarian, []),
          ]}
          color={useCallback((_, i) => legendItems[i].color, [])}
        />
        <VisAxis type="x" label="Election Year" numTicks={data.length}/>
        <VisAxis
          type="y"
          tickFormat={useCallback((value: number) => (value / 10 ** 6).toFixed(1), [])}
          label="Number of Votes (millions)"/>
      </VisXYContainer>
    </>
  )
}

// packages/shared/examples/basic-grouped-bar/basic-grouped-bar.svelte
<script lang="ts">
  import { VisXYContainer, VisGroupedBar, VisAxis, VisBulletLegend } from '@unovis/svelte'
  import type { ElectionDatum } from './data'
  import { data, colors, capitalize } from './data'

  const items = Object.entries(colors).map(([n, c]) => ({
    name: capitalize(n),
    color: c,
  }))
  const x = (d: ElectionDatum) => d.year
  const y = [
    (d: ElectionDatum) => d.republican,
    (d: ElectionDatum) => d.democrat,
    (d: ElectionDatum) => d.other,
    (d: ElectionDatum) => d.libertarian,
  ]
  const color = (d: ElectionDatum, i: number) => items[i].color
</script>

<h2>U.S. Election Popular Vote Results by Political Party</h2>
<VisBulletLegend {items}/>
<VisXYContainer height={500}>
  <VisGroupedBar {data} {x} {y} {color} />
  <VisAxis type="x" label="Election Year" numTicks={data.length}/>
  <VisAxis
    type="y"
    tickFormat={(value) => (value / 10 ** 6).toFixed(1)}
    label="Number of Votes (millions)"/>
</VisXYContainer>
