// packages/website/src/examples/single-level-chord-diagram/single-level-chord-diagram.tsx
import React, { useCallback } from 'react'
import { VisSingleContainer, VisChordDiagram } from '@unovis/react'
import { ChordLabelAlignment } from '@unovis/ts'

import { nodes, links, NodeDatum, LinkDatum } from './data'

export default function SingleLevelChordDiagram (): JSX.Element {
  return (
    <VisSingleContainer data={{ links, nodes }} height={'60vh'}>
      <VisChordDiagram<NodeDatum, LinkDatum>
        linkColor={useCallback((l: LinkDatum): string => l.source.color)}
        nodeLabel={useCallback((n: NodeDatum): string => n.id, [])}
        nodeLabelAlignment={ChordLabelAlignment.Perpendicular}
      />
    </VisSingleContainer>
  )
}

// packages/website/src/examples/single-level-chord-diagram/single-level-chord-diagram.svelte
<script lang='ts'>
  import { VisSingleContainer, VisChordDiagram } from '@unovis/svelte'
  import { ChordLabelAlignment } from '@unovis/ts'
  import { links, nodes, LinkDatum, NodeDatum } from './data'

  const data = { links, nodes }
  const linkColor = (l: LinkDatum) => l.source.color
  const nodeLabel = (n: NodeDatum) => n.id
</script>

<VisSingleContainer data={data} height={'60vh'}>
  <VisChordDiagram
    {linkColor}
    {nodeLabel}
    nodeLabelAlignment={ChordLabelAlignment.Perpendicular}
  />
</VisSingleContainer>
