// packages/website/src/examples/single-level-chord-diagram/single-level-chord-diagram.svelte
<script lang='ts'>
  import { VisSingleContainer, VisChordDiagram } from '@unovis/svelte'
  import { ChordLabelAlignment } from '@unovis/ts'
  import { links, nodes, LinkDatum, NodeDatum } from './data'

  const data = { links, nodes }
  const linkColor = (l: LinkDatum) => l.source.color
  const nodeLabel = (n: NodeDatum) => n.id
</script>

<VisSingleContainer data={data} height={'60vh'}>
  <VisChordDiagram
    {linkColor}
    {nodeLabel}
    nodeLabelAlignment={ChordLabelAlignment.Perpendicular}
  />
</VisSingleContainer>

// packages/website/src/examples/single-level-chord-diagram/single-level-chord-diagram.component.ts
import { Component } from '@angular/core'
import { ChordLabelAlignment } from '@unovis/ts'
import { nodes, links, NodeDatum, LinkDatum } from './data'

@Component({
  selector: 'single-level-chord-diagram',
  templateUrl: './single-level-chord-diagram.component.html',
})
export class SingleLevelChordDiagramComponent {
  data: {
    nodes: NodeDatum[];
    links: LinkDatum[];
  } = { nodes, links }

  linkColor = (l: LinkDatum): string => l.source.color
  nodeLabel = (n: NodeDatum): string => n.id
  nodeLabelAlignment = ChordLabelAlignment.Perpendicular
}

<vis-single-container [data]="data" height="60vh">
    <vis-chord-diagram
      [linkColor]="linkColor"
      [nodeLabel]="nodeLabel"
      [nodeLabelAlignment]="nodeLabelAlignment"
    ></vis-chord-diagram>
</vis-single-container>
