// packages/shared/examples/basic-line-chart/basic-line-chart-solid.tsx
import { JSX } from 'solid-js'
import { VisAxis, VisLine, VisXYContainer } from '@unovis/solid'

import { data } from './data'

const BasicLineChart = (): JSX.Element => {
  return (
    <VisXYContainer height='50dvh'>
      <VisLine data={data} x={(d) => d.x} y={(d) => d.y} />
      <VisAxis type='x' />
      <VisAxis type='y' />
    </VisXYContainer>
  )
}

export default BasicLineChart

// packages/website/src/examples/basic-line-chart/basic-line-chart.tsx
import React, { useCallback } from 'react'
import { VisXYContainer, VisLine, VisAxis } from '@unovis/react'

import { data } from './data'

export default function BasicLineChart (): JSX.Element {
  return (
    <VisXYContainer height={600}>
      <VisLine
        data={data}
        x={useCallback(d => d.x, [])}
        y={useCallback(d => d.y, [])}
      ></VisLine>
      <VisAxis type="x"></VisAxis>
      <VisAxis type="y"></VisAxis>
    </VisXYContainer>
  )
}
